### ISSUE TITLE
Autocomplete field with create new function

### ISSUE THREAD

**Issue by npull** [code16/sharp#100]
Let's say we want to create a new book with an author that we select with an autocomplete field, it searches an author table for the correct author. If it does not find the author of the book we dont want to abort and first create a new author then go back and start over to create the book. Is there anyway to solve this with Sharp? Ideally there would be an autocomplete field that also takes input that does not exist in the source and handles it in the update method by creating a new author before saving. A bit like wordpress taxonomy tags work I suppose.

**Comment by dvlpp** [comment]
No, autocomplete field can not do this out of the box, for a least two good reasons: first the linked data (a Model, in many cases) could rarely be created with only one text value, and second an autocomplete can be configured as remote, meaning the data come from an external endpoint...

(Note that the Tags field (https://github.com/code16/sharp/blob/master/docs/form-fields/tags.md) can do this on-the-fly creation — in this case le linked data is often simply a string value)

In a situation like this, what you could do is add a checkbox labelled "New author", which when clicked displays the author required fields (maybe `first_name` and `last_name`?) and hides the autocomplete field. This can be easily done with [conditional display](https://github.com/code16/sharp/blob/master/docs/building-entity-form.md#conditional-display). And in your `update($data)` method of your `SharpForm` implementation, you can do what's needed to be done to first create the author.

Even better, maybe, if you are in a `belongsTo` relation, and you are using Sharp's `WithSharpFormEloquentUpdater` feature, you can leave the update part to Sharp using the `:` separator trick (https://github.com/code16/sharp/blob/master/docs/how-to-transform-data.md#the--separator-and-transformers). In this case, with a relation named `author`, you could define fields like this to let Sharp handle the update process:

```
function buildFormFields()
{
    $this->addField(SharpFormTextField::make("author:first_name"));
    $this->addField(SharpFormTextField::make("author:last_name"));
}
```

**Comment by npull** [comment]
Thanks for the insights! I think I'll be able to come up with a solution with your tips. As a side note, the tags.md file has a typo the setMaxTagsCount method is actually named setMaxTagCount. And there is no constructor in the .md file so I had to go to the source code to see how it works.
