### ISSUE TITLE
SelectForm Multiple Checked Values

### ISSUE THREAD

**Issue by rokkay** [code16/sharp#101]
Hello again, I have a form with days of the week in a selection field with setMultiple. When I modify the registry, I want to be able to mark or unmark the days of the week but, by default, all are unchecked, I can not find any way to do it. I searched the [docs](https://github.com/code16/sharp/blob/master/docs/form-fields/select.md) but I have not seen any method to select the default fields. Maybe i'm forgotten something? I want to select the corresponding values when i retrieve the model. Can i do this with a transformer?

![imagen](https://user-images.githubusercontent.com/47890402/53798723-1a64a500-3f39-11e9-8e4a-8a2f10b6a027.png)

Here's my code:

**Array with days of the week**
`        $diasSemana = [
            1 => __('forms.actividad.dias.lunes'),
            2 => __('forms.actividad.dias.martes'),
            3 => __('forms.actividad.dias.miercoles'),
            4 => __('forms.actividad.dias.jueves'),
            5 => __('forms.actividad.dias.viernes'),
            6 => __('forms.actividad.dias.sabado'),
            7 => __('forms.actividad.dias.domingo'),
        ];`

**Add field**
`->addField(
            SharpFormSelectField::make("dias_semana", $diasSemana)
            ->setLabel(__('forms.actividad.dias.semana'))
            ->setMultiple()
            ->setDisplayAsList()
        )`

Thanks in advance.

**Comment by dvlpp** [comment]
If I understand you well, you need to check some fields by default on a creation case? If so, you can add a `create()` method in your form to initiate values. For instance, with Eloquent (using `MyModel` for the model of the entity):

```
public function create(): array
{
    return $this->transform(new MyModel([
        'dias_semana' => [1,2,3,4,5]
    ]));
}
```

If `dias_semana` is not an attribute of the model, use a custom transformer:

```
public function create(): array
{
    return $this
        ->setCustomTransformer('dias_semana', function() {
            return [1,2,3,4,5];
        })
        ->transform(new MyModel);
}
```

**Comment by rokkay** [comment]
Thanks for reply, i created a custom transformer:
```
    function find($id): array
    {

        return $this->setCustomTransformer(
            "dias_semana", function($diasSemana){
                return array_map('intval', explode(' ', $diasSemana));
            }
        )->transform(
            Actividad::with(["programa", "condiciones", "fotos"])->findOrFail($id)
        );
    }
```
And to save it i have converted the array to string. Now works well.

**Comment by dvlpp** [comment]
Ah, sorry, I thought it was in a `Form`; it's an `EntityList`, based on your comment. Glad you found a way.
