### ISSUE TITLE
Support images in wysiwyg editor

### ISSUE THREAD

**Issue by trister1997** [code16/sharp#105]
Is there any plan to support images in the wysiwyg editor? I see that I can drag and drop images in the editor, but when I save it does nothing. So im assuming the code to handle the drag and drop event is not setup?

**Comment by dvlpp** [comment]
Well, the Markdown editor can embed images (https://github.com/code16/sharp/blob/master/docs/form-fields/markdown.md#embed-images-in-markdown), but the wysiwyg editor is not yet able to handle it. We certainly plan to support this feature, but I don’t know when...

**Comment by trister1997** [comment]
When the markdown editor embeds images, if I serve the data over an API to a mobile application, will it still show the image? I looked at the html it produced and wasnt sure how that worked.

**Comment by dvlpp** [comment]
Yes, you can create a thumbnail and return an custom url (see "Display those images as thumbnail in the public site" in the doc).

**Comment by staniktomas** [comment]
What is progress with this "enhancement"? Current Trix editor allows file attachments. But it's not implemented in sharp. Or should I join Sharp development, currently our project really depends on this feature.

**Comment by dvlpp** [comment]
@staniktomas We intend to make this possible, but it's not a priority right now. But you can definitively write a PR for this: be sure to look to the implementation we made for the Markdown field, because it's not really a front topic, this has much to do with the uploaded file handling on the back.

**Comment by staniktomas** [comment]
If I'll have some extra time, definitely will check this out.

**Comment by dvlpp** [comment]
This is addressed in Sharp 7
