### ISSUE TITLE
How to customize the User Interface

### ISSUE THREAD

**Issue by uwascan** [code16/sharp#127]
Hello, This is a wonderful and very mature alternative to Laravel Nova. But I am having issues customizing the user interface. Any guide or online resource will be ok.

Please do not limit Sharp to building just backends to blogs and CMSes, this is a valid platform for build SPAs and Apps. I am spreading the news to my team mates.
Good Job

**Comment by dvlpp** [comment]
By "Customizing the user interface", you mean redefining CSS? It's not in our plans, for now: the CSS part is still moving, and we'll have too many breaking changes — I don't want to be blocked by this kind of consideration when building a new feature...
