### ISSUE TITLE
Poor guide for begginers

### ISSUE THREAD

**Issue by kulyklev** [code16/sharp#142]
Please make clear guide for sharp instalation. Because it is not straightforward. I can't understand do I have to run your migrations to add 'login' field or should i write migration myself. Then, before running `php artisan vendor:publish --provider="Code16\Sharp\SharpServiceProvider" --tag=assets` I ran `php artisan package:discover`, because publish command had no effect before that. I hope you will improve your instalation guide soon

**Comment by dvlpp** [comment]
I think you should start with a guided tour, to understand the concepts. I wrote one, in 6 parts, starting here: https://medium.com/code16/about-sharp-for-laravel-part-1-74a826279fe0
