### ISSUE TITLE
Form page without list

### ISSUE THREAD

**Issue by Resin01** [code16/sharp#144]
Is there a way to add a Form without a list. Say I want a form for setting up the items in the footer. These will only be one instance, so I dont want a list. I also dont want the user to be able to delete it the whole thing :)
Alternatively, is it possible to disallow deleting in form (not just have an empty delete method)

**Comment by dvlpp** [comment]
You can't skip the list, no. But you can of course forbid deletion, creation and anything between, for everyone (global) or not (policies). See https://sharp.code16.fr/docs/guide/entity-authorizations.html#available-permissions
