### ISSUE TITLE
Add ability to select/deselect all on a multi-selection SharpFormSelectField

### ISSUE THREAD

**Issue by nsrosenqvist** [code16/sharp#157]
It'd be great if there was an option to show two link buttons that allows toggling all items in a multi-select field.

_Example:_
![Screenshot_2019-07-31 Handball sample, Roles Sharp 4 1 16](https://user-images.githubusercontent.com/1303475/62200743-52f09980-b386-11e9-8a68-72e1ea57f0b1.png)

**Comment by dvlpp** [comment]
Feature to be discussed.
