### ISSUE TITLE
SelectFormatter messes up keys when casting to array

### ISSUE THREAD

**Issue by nsrosenqvist** [code16/sharp#158]
If I pass a model instance to `SharpForm::transform` everything works as it should, but if I first cast it to an array to be able to manually set properties on the data passed to the frontend Sharp gives the error message `Undefined index: id`. I debugged the issue and found that the the _SelectFormatter_ casts a model in the dataset to an array in _Code16\Sharp\Form\Fields\Formatters\SelectFormatter_ line 19 and it messes up its attribute keys. This is the output you get in artisan tinker when you cast and convert an Eloquent model respectively:

_cast:_
```
>>> (array) Role::find(1)
=> [
     "\0*\0guarded" => [
       "id",
     ],
     "\0*\0connection" => "sqlite",
     "\0*\0table" => "roles",
     "\0*\0primaryKey" => "id",
     "\0*\0keyType" => "int",
     "incrementing" => true,
     "\0*\0with" => [],
     "\0*\0withCount" => [],
     "\0*\0perPage" => 15,
     "exists" => true,
     "wasRecentlyCreated" => false,
     "\0*\0attributes" => [
       "id" => "1",
       "name" => "Admin",
       "guard_name" => "web",
       "created_at" => "2019-07-27 16:12:54",
       "updated_at" => "2019-07-27 16:12:54",
     ],
     "\0*\0original" => [
       "id" => "1",
       "name" => "Admin",
       "guard_name" => "web",
       "created_at" => "2019-07-27 16:12:54",
       "updated_at" => "2019-07-27 16:12:54",
     ],
     "\0*\0changes" => [],
     "\0*\0casts" => [],
     "\0*\0dates" => [],
     "\0*\0dateFormat" => null,
     "\0*\0appends" => [],
     "\0*\0dispatchesEvents" => [],
     "\0*\0observables" => [],
     "\0*\0relations" => [],
     "\0*\0touches" => [],
     "timestamps" => true,
     "\0*\0hidden" => [],
     "\0*\0visible" => [],
     "\0*\0fillable" => [],
     "\0Spatie\Permission\Models\Role\0permissionClass" => null,
   ]
```

_convert:_
```
>>> Role::find(1)->toArray()
=> [
     "id" => 1,
     "name" => "Admin",
     "guard_name" => "web",
     "created_at" => "2019-07-27 16:12:54",
     "updated_at" => "2019-07-27 16:12:54",
   ]
```

So it becomes clear why the index "id" provided by `$field->idAttribute()` is undefined. I don't know why this cast wouldn't cause the same error when passing a model instance to `transform` since I'm not familiar with the code path yet. The dataset that I'm passing to `transform` is a model as an array with a custom property containing an array of models, e.g.:

```php
    function buildFormFields()
    {
        $this->addField(
            SharpFormSelectField::make("custom", ["id" => 1, "label" => "one"])
                 ->setDisplayAsList()
                 ->setMultiple()
                 ->setInline()
        );
    }

    function buildFormLayout()
    {        
        $this->addColumn(12, function (FormLayoutColumn $column) {
            $column->withSingleField('custom');
        });  
    }

    function find($id): array
    {
        $user = User::find(1)->toArray();
        $user['custom'] = [
            User::find(2),
            User::find(3),
        ];

        return $this->transform($user);
    }
```

**Comment by dvlpp** [comment]
I don't understand your case; you wrote:
> So it becomes clear why the index "id" provided by $field->idAttribute() is undefined
I don't see why it's clear? The id is defined in the `Role` casted into an array.

Thus I see a common mistake in your `SharpFormSelectField` creation. Either you choose to use the `id=>value` syntax, for instance:

`SharpFormSelectField::make("custom", [1 => "One", 2 => "Two"])`

Or the `"id"=>id,"value"=>value` syntax, which seems to be your case, but you'll then need an array of arrays:

`SharpFormSelectField::make("custom", [["id"=>1, "label"=>"One"], ["id"=>2,"label"=>"Two"]])`

Is this related to your issue? If not, can you provide the full Form code?

**Comment by nsrosenqvist** [comment]
No, I'm afraid you misunderstand me. The issue has nothing to do with populating the select field's options (my sample code was unfortunately incorrectly formatted). The issue is with how the select field is unable to correctly populate the saved options provided in `find` when one passes an array to `transform` rather than a model instance.

What I'm trying to do is to manually provide a value that is not a property of the model and one cannot set a custom property of a model instance and therefore one requires to first convert it to an array. This works perfectly fine except when I set an array of models for the SelectFormatter.

This works:
```php
    function buildFormFields()
    {
        $this->addField(
            SharpFormTextField::make("custom_text")
        );
    }

    function buildFormLayout()
    {        
        $this->addColumn(12, function (FormLayoutColumn $column) {
            $column->withSingleField('custom_text');
        });  
    }

    function find($id): array
    {
        $user = User::find($id)->toArray(); // Converted to array
        $user['custom_text'] = 'Oh yeah!';

        return $this->transform($user);
    }
```

The following doesn't work even though SelectFormatter should support an array of models according to the documentation that says that `toFront` expects "an array of id values OR an array of models if multiple=true":

```php
    function buildFormFields()
    {
        $this->addField(
            SharpFormTextField::make("custom_text")
        )->addField(
            SharpFormSelectField::make("custom", [
                ["id" => 1, "label" => "one"],
                ["id" => 2, "label" => "two"],
                ["id" => 3, "label" => "three"],
                ])
                 ->setDisplayAsList()
                 ->setMultiple()
                 ->setInline()
        );
    }

    function buildFormLayout()
    {        
        $this->addColumn(12, function (FormLayoutColumn $column) {
            $column->withSingleField('custom_text');
            $column->withSingleField('custom');
        });  
    }

    function find($id): array
    {
        $user = User::find($id)->toArray();
        
        $user['custom_text'] = 'Oh yeah!';
        $user['custom'] = [
            User::find(1),
            User::find(2),
            User::find(3),
        ];

        return $this->transform($user);
    }
```

If I would pass a model to `transform` that has a hasMany relationship called "custom" then it wouldn't cause an error, but when I first convert it to an array and set an array of models myself (that should be perfectly fine according to the docs), then the transform code errors out on line 19 (SelectFormatter.php) because it tries to access the index "id" of a model that it has cast to an array:

```php
    function toFront(SharpFormField $field, $value)
    {
        if($field->multiple()) {
            return collect((array)$value)->map(function($item) use($field) {
                return is_array($item) || is_object($item)
                    ? ((array)$item)[$field->idAttribute()] // <--- This right here
                    : $item;
            })->all();

        } elseif(is_array($value)) {
            // Strip other values is not configured to be multiple
            return $value[0];
        }

        return $value;
    }
```

Since the model is just cast to an array and not converted using `toArray` it doesn't have "id" as an index, it's in fact found in `["\0*\0attributes"]["id"]`.

---

Here is the code as a class that can be used to test the error:  

```php
<?php

namespace App\Sharp;

use App\User;
use Code16\Sharp\Form\Fields\SharpFormTextField;
use Code16\Sharp\Form\Fields\SharpFormSelectField;
use Code16\Sharp\Form\Layout\FormLayoutColumn;
use Code16\Sharp\Form\SharpForm;

class RoleForm extends SharpForm
{
    function buildFormFields()
    {
        $this->addField(
            SharpFormTextField::make("custom_text")
        )->addField(
            SharpFormSelectField::make("custom", [
                ["id" => 1, "label" => "one"],
                ["id" => 2, "label" => "two"],
                ["id" => 3, "label" => "three"],
                ])
                 ->setDisplayAsList()
                 ->setMultiple()
                 ->setInline()
        );
    }

    function buildFormLayout()
    {        
        $this->addColumn(12, function (FormLayoutColumn $column) {
            $column->withSingleField('custom_text');
            $column->withSingleField('custom');
        });  
    }

    function find($id): array
    {
        $user = User::find($id)->toArray();
        $user['custom_text'] = 'Oh yeah!';
        $user['custom'] = [
            User::find(1),
            User::find(2),
            User::find(3),
        ];

        return $this->transform($user);
    }

    function update($id, array $data)
    {
        // ...
    }

    function delete($id)
    {
        // ...
    }
}
```

**Comment by dvlpp** [comment]
Ah I see, thanks for your complete explanation. `SelectFormatter::toFront` code is badly written, and it made me realize that this issue is true for other parts of the codebase. I made a PR (https://github.com/code16/sharp/pull/165) to fix this, that I will merge soon (after a few mode tests).

**Comment by nsrosenqvist** [comment]
That's great! Thanks for your quick response!
