### ISSUE TITLE
Saving uploads doesn't work with SharpUploadModel when it's a subattribute

### ISSUE THREAD

**Issue by nsrosenqvist** [code16/sharp#160]
If a subattribute to a model is specified as a field (e.g. "profile:avatar") then _SharpUploadModel_ fails to save it as the _HasOneRelationUpdater_ attempts to set the attribute directly rather than use `HasOneRelationUpdater::createRelatedModel()`:

_HasOneRelationUpdater_ **line 19-27**
```php
            if($instance->$attribute) {
                $instance->$attribute->$subAttribute = $value;
                $instance->$attribute->save();

            } elseif($value) {
                $this->createRelatedModel(
                    $instance, $attribute, [$subAttribute => $value]
                );
            }
```

This can be worked around by ignoring the field and saving it separately:
```php
$this->ignore(['profile:avatar'])->save($instance, $data);
$this->save($instance->profile, ['avatar' => $data['profile:avatar']]);
```

Unfortunately it still doesn't work properly as _FormUploadModelTransformer_ aborts if it doesn't find the key directly on the model. So even though it can save with the workaround it doesn't display without reimplementing the entire logic of _FormUploadModelTransformer_ (it's the same with _SharpUploadModelAttributeTransformer_):

_FormUploadModelTransformer_ **line 21-23**
```php
        // Here "profile:avatar" is submitted as $attribute
        if(!$instance->$attribute) {
            return null;
        }
```

**Comment by dvlpp** [comment]
Well, the `:` "magic" trick can only be used, in any kind of relationship, for a simple attribute, and not for another relation. In other words: you can use `profile:name`, but not `profile:avatar`, since `avatar` is not an attribute on a sub relation.
