### ISSUE TITLE
Help integrating the Upload field with spatie/laravel-medialibrary

### ISSUE THREAD

**Issue by panda-madness** [code16/sharp#171]
Hello.
I'm trying to integrate the upload field with [spatie/laravel-medialibrary](https://github.com/spatie/laravel-medialibrary). I've been able to add new media files, but I'm having trouble feeding back already existing media to the front end. I've tried adding an `images` attribute to my model (the field in the Sharp form is also called `images`), but I'm just getting a bunch of empty fields, instead of image previews.
![2019-08-23 1566559225](https://user-images.githubusercontent.com/6180087/63589286-8a8be380-c5ca-11e9-9c0e-a11b842f7622.png)

I suspect that this approach can work, and I'm just generating the wrong JSON schema in the `images` field.

Any help with this would be appreciated. Figuring out and documenting this use case would be useful, to enable a more generic way of handling media.

**Comment by dvlpp** [comment]
I think it has to do with the data transformation (on the `find($id)` function of the Form), but I don't have enough information to understand the cas. Could you post the full Form code?

**Comment by panda-madness** [comment]
Here's the form class code:
```
<?php


namespace App\Admin\Products;


use Code16\Sharp\Form\Fields\SharpFormListField;
use Code16\Sharp\Form\Fields\SharpFormSelectField;
use Code16\Sharp\Form\Fields\SharpFormTextField;
use Code16\Sharp\Form\Fields\SharpFormUploadField;
use Code16\Sharp\Form\Layout\FormLayoutColumn;
use Code16\Sharp\Form\SharpForm;
use Domain\Catalog\Models\Category;
use Domain\Catalog\Models\Product;

class ProductSharpForm extends SharpForm
{

    /**
     * Retrieve a Model for the form and pack all its data as JSON.
     *
     * @param $id
     * @return array
     */
    function find($id): array
    {
        return $this->transform(Product::find($id));
    }

    /**
     * @param $id
     * @param array $data
     * @return mixed the instance id
     */
    function update($id, array $data)
    {
        $product = Product::findOrFail($id);

        if(isset($data['images'])) {
            collect($data['images'])->each(function(array $image) use($product) {
                $product->addMedia(
                    storage_path($image['image']['file_name'])
                );
            });

            unset($data['images']);
        }

        $product->update($data);

        return $product->id;
    }

    /**
     * @param $id
     * @throws \Exception
     */
    function delete($id)
    {
        Product::findOrFail($id)->delete();
    }

    /**
     * Build form fields using ->addField()
     *
     * @return void
     */
    function buildFormFields()
    {
        $this->addField(
            SharpFormTextField::make('name')
                ->setLabel('Название')
                ->setLocalized(true)
        );

        $this->addField(
            SharpFormSelectField::make('category_id',
                Category::all()->map(function (Category $category) {
                    return [
                        'id' => $category->id,
                        'label' => $category->name
                    ];
                })->toArray())
                ->setLabel('Категория')
                ->setDisplayAsDropdown()
        );

        $this->addField(
            SharpFormListField::make('images')
            ->setLabel('Картинки')
            ->setAddable()
            ->setRemovable()
            ->addItemField(
                SharpFormUploadField::make('image')
                ->setFileFilterImages()
            )
        );
    }

    /**
     * Build form layout using ->addTab() or ->addColumn()
     *
     * @return void
     */
    function buildFormLayout()
    {
        $this->addColumn(6, function (FormLayoutColumn $column) {
            $column->withSingleField('name');
        });

        $this->addColumn(6, function (FormLayoutColumn $column) {
            $column->withSingleField('category_id');
        });

        $this->addColumn(12, function (FormLayoutColumn $column) {
            $column->withSingleField('images', function(FormLayoutColumn $listItem) {
                $listItem->withSingleField('image');
            });
        });
    }

    public function getDataLocalizations()
    {
        return ['ru', 'kz'];
    }
}
```

This is what I'm doing in my model:
```
class Product extends BaseModel implements HasMedia {
...
    protected $fillable = ['name', 'category_id'];
    protected $appends = ['images'];
...
    public function getImagesAttribute()
    {
        return $this->getMedia()->map(function(Media $media) {
            return [
                'id' => $media->id,
                'image' => $media->getPath()
            ];
        });
    }
...
```

**Comment by dvlpp** [comment]
OK, I see 2 things:
- first, I would not create a specific `getImagesAttribute()` method in a Model for Sharp — which idea is to leave the project code alone. Transformers are here for this kind of stuff;
- second, each form field type needs its data to be formatted for the front in sharp. For uploads, here's the expected data, with an example: https://sharp.code16.fr/docs/guide/form-fields/upload.html#formatter

So in your case, something like this:

```php
function find($id): array
{
    return $this->setCustomTransformer("image",
        function($value, $product, $attribute) {
            return [
                "name" => $product->image->name, // Or equivalent
                "thumbnail" => [...],
                "size" => $spaceship->image->size, // Or equivalent
            ];
        })
        ->transform(
            Product::findOrFail($id)
        );
}
```

Since you are not leveraging `SharpUploadModel` which does all this automatically ([see here](https://sharp.code16.fr/docs/guide/sharp-built-in-solution-for-uploads.html#use-sharpuploadmodel)), you'll have to implement partly this stuff yourself—which is ok, should be not too painful. You'll also have to do the work on `update()` method (the `fromFront` part: https://sharp.code16.fr/docs/guide/form-fields/upload.html#formatter)

**Comment by panda-madness** [comment]
For some reason I did not figure out that the Formatter sections describe exactly what I needed.
Here is the final transformation that I had to do to make a `List` field (`images`) consisting of an `Upload` field (`image`) work correctly:
```
return $this
            ->setCustomTransformer('images', function($value, Product $product, $attribute) {
                return $product->getMedia()->map(function(Media $media) {
                    return [
                        'id' => $media->id,
                        'image' => [
                            'name' => $media->getPath(),
                            'thumbnail' => $media->getFullUrl(),
                            'size' => $media->size,
                        ]
                    ];
                })->toArray();
            })
            ->transform(Product::findOrFail($id));
```

**Comment by dvlpp** [comment]
I'm glad that you could find a way. 

Last advice: you can extract this code to a dedicated Transformer class, to use it elsewhere (here's an example: https://github.com/code16/sharp/blob/master/src/Form/Eloquent/Transformers/FormUploadModelTransformer.php). Then you could simply call:

`->setCustomTransformer("images", new MediaTransformer())`

Just in case: I would be happy if you could share, via a blog post for instance, your findings on using Sharp with Spatie Media library. Maybe it could be useful for others.
