### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by Kovah** [code16/sharp#174]
Just wanted to inform you that the demo is not working at the moment. Logging in with any credentials leads to the "Something went wrong" error screen.

**Comment by dvlpp** [comment]
Thanks; it's working now.

**Comment by Kovah** [comment]
Awesome, thank you very much. Excited to try out Sharp!

**Comment by dvlpp** [comment]
Yeah, that was my fault... I updated the code to be Laravel 6 compliant, and Saturn kept old view cache, and an invalid `str_random` in a factory. I fixed it.

**Comment by Kovah** [comment]
Had the exact same issue with one of my apps after updating to L6. Thank for your fast response.
