### ISSUE TITLE
EntityList table headers don't align properly

### ISSUE THREAD

**Issue by BramEsposito** [code16/sharp#179]
![image](https://user-images.githubusercontent.com/168336/64856689-e2929480-d622-11e9-890c-739b45bef7e8.png)
Screenshot from: https://sharp.code16.fr/sharp/list/passenger

The column headers are narrower than the columns themselves, as you can see in the screenshot.

**Comment by BramEsposito** [comment]
I fixed this in Sass, but after running ```npm run production``` I have a large diff on the dist files. 

Can I create a Pull request with only the changes in Sass and let you rebuild the webpacked files?

**Comment by dvlpp** [comment]
No, this is already fixed in master actually (#167). I'll build a new version soon.

**Comment by dvlpp** [comment]
This is still an issue in 4.1.18

**Comment by dvlpp** [comment]
Well, it's not actually. I forgot to build assets on the 4.1.18 version, just deployed a 4.1.19 for this. Like a pro®.
