### ISSUE TITLE
[Discussion] Retain (and show) values in SharpFormTagsField upon edit

### ISSUE THREAD

**Issue by chadedge** [code16/sharp#183]
This appears to "just be me" (when comparing to demo code), but when using a SharpFormTagsField I'm unable to view the "already selected/saved" entities against my model.
I've compared to the SpaceshipForm (in regards to pilots) and can see there when editing an entity the "already selected" items are shown in the TagsField.

In my situation, I have an entity "Event" that has a HasMany(App\Activity) relationship (an Event is a job position, and the activities are the duties completed while at the job). When creating/updating the entity via a form class the values are stored in the db, but not shown when editing the same entity.

```
... ->addField(
SharpFormTagsField::make("activities",
Activity::orderBy("name")->get()->pluck("name","id")->all())
->setCreatable(false)
->setLabel("Activities")
);
```

When I try to use a context() I get back _only_ the already related models (but again not shown in the form, just selectable).
```
Event::find($this->context()->instanceId())->activities->toArray()
```

I'm sure I'm missing something by following the sample code (this is very similar to Spaceship hasMany Pilots), I'm just lost on making sure - on edit - that the data is present and pre-selected.

Thoughts?

**Comment by dvlpp** [comment]
Mmm, did you said the relation is a HasMany? If so, that's a pretty huge difference: Spaceships and Pilots are bound through a BelongsToMany relation, for which the "natural" from input is tags.

In a HasMany, you'll want to implement either a List, or an [AutocompleteList](https://sharp.code16.fr/docs/guide/form-fields/autocomplete-list.html), depending on the situation.

**Comment by chadedge** [comment]
Good catch. I checked my model and is has an activities() { return $this->belongsToMany('App\Activity'); } method on it (which matches the Spaceship model).
I double-checked my schema, I do have an "activity_event" pivot table, and it's getting updated correctly when I alter my entity, and on my list I'm seeing the correct items listed. Still, the edit form is not showing the existing items selected.

```
// EventSharpForm.php
$this->addField(
      SharpFormTagsField::make("activities",
        Activity::orderBy("name")->get()->pluck("name","id")->all()
      )
      ->setLabel("Activities")
      ->setCreatable(true)
      ->setCreateAttribute("name")
      ->setMaxTagCount(4)
    );
```
```
// Event.php model
public function activities()
{
  return $this->belongsToMany('App\Activity');
}

// Activity.php model
// Note: I've tried removing this method too.
public function events()
{
  return $this->belongsToMany('App\Event');
}
```

```
// EventSharpList.php
getListData(EntityListQueryParams $params)
{
...
->setCustomTransformer("activities", function ($activities, $event) {
  // @todo: convert to a map return.
  $acts[];
  foreach ($activities as $activity) {
    $acts[] = $activity['name'];
  }
  return implode(", ", $acts);
})->transform($events->with('place' ,'activities')->paginate(30));
}
```

EventSharpList.php returns me a well-formatted set of rows with the event role, position, etc and a comma-sep of the "activities" this person conducted while in that role (as expected).

**Comment by dvlpp** [comment]
Could you post your form’s find() code? I suspect you forgot to load the relation (I mean ˋ->with("activities")`)

**Comment by chadedge** [comment]
```
class EventSharpForm extends SharpForm
{
...

  function find($id): array
  {
    return $this->transform(Event::findOrFail($id)->with('activities'));
  }
}
```
I added the "with('activities')" just to test and am getting the same results.
I've also run a dump-autoload and rebuild (working locally via Lando as my build environment).
Oddly enough, if I add ->with('activities') I lose the data for the event itself (Event has 'role,' 'description,' 'start_date,' 'end_date'). Event->place() exists, however.

Sorry to keep this going, I'm confident I'm missing something here, it's just a strange occurrence.

**Comment by chadedge** [comment]
I'm such a dope. As soon as I pasted the above I reversed the order on the find.
This version works:
```
  function find($id): array
  {
    return $this->transform(Event::with('place','activities')->findOrFail($id));
  }
```
(note that I put the with _before_ the findOrFail() ).

**Comment by dvlpp** [comment]
Ok. Glad it’s working now
