### ISSUE TITLE
Pie Charts actually still not working properly, at least not for me. v4.1.19 - laravel v6.0.4

### ISSUE THREAD

**Issue by staniktomas** [code16/sharp#184]
My pie chart code:
```
    protected function buildWidgets()
    {
        $this->addWidget(
            SharpPieGraphWidget::make("capacities_pie")
                ->setTitle("Spaceships by capacity")
        );
    }

    protected function buildWidgetsLayout()
    {
        $this->addRow(function (DashboardLayoutRow $row) {
            $row->addWidget(6, "capacities_pie");
        });
    }

    protected function buildWidgetsData(DashboardQueryParams $params)
    {
        $this->addGraphDataSet(
            "capacities_pie",
            SharpGraphWidgetDataSet::make([
                rand(1, 3)
            ])
                ->setLabel("Capacities 1")
                ->setColor("#3e9651")
        );
        $this->addGraphDataSet(
            "capacities_pie",
            SharpGraphWidgetDataSet::make([
                rand(2, 6)
            ])
                ->setLabel("Capacities 2")
                ->setColor("#6b4c9a")
        );
        $this->addGraphDataSet(
            "capacities_pie",
            SharpGraphWidgetDataSet::make([
                rand(4, 9)
            ])
                ->setLabel("Capacities 3")
                ->setColor("#2d2d2d")
        );
    }
```
Expectations:
<img width="553" alt="Screenshot 2019-09-30 at 21 15 14" src="https://user-images.githubusercontent.com/12097108/65908815-858b3280-e3c7-11e9-9876-d1446f935f86.png">

Result: 
<img width="409" alt="Screenshot 2019-09-30 at 21 11 25" src="https://user-images.githubusercontent.com/12097108/65908705-45c44b00-e3c7-11e9-986f-6ce00c13e11f.png">

**Comment by dvlpp** [comment]
I think you don't have the latest version of assets? Please run `php artisan vendor:publish --provider="Code16\Sharp\SharpServiceProvider" --tag=assets` ans retry.
(And notice that you could do that on each update: https://sharp.code16.fr/docs/guide/#installation)

**Comment by staniktomas** [comment]
Script was already in `"post-autoload-dump"` and working properly. I tried it again manually after your advice, published - nothing changed.

**Comment by dvlpp** [comment]
Ah, I'm not sure then... This issue looks smells a lot like "assets are old". I can't think of another cause... Maybe you should try to delete `public/vendor/sharp`, rerun `php artisan vendor:publish --provider="Code16\Sharp\SharpServiceProvider" --tag=assets` and reload your page without cache, just to be sure?

**Comment by staniktomas** [comment]
**Deleting `public/vendor/sharp`** is the key, **before publishing .** Cache was cleared before re-publishing, it didn't help.
