### ISSUE TITLE
Configuration problem

### ISSUE THREAD

**Issue by vdf89** [code16/sharp#187]
Hello.
I started to use Sharp in a laravel application but I have found a problem on configuration.
The problem is that the various CSS and JS files are not linked in the right way. I have to manually edit the file in vendor/code16/sharp/resources/views/layout.blade.php to add "../" before the value in the "href" and "src" attributes, in order to make them work, otherwise the final URLs in the browser are pointing at http://localhost/vendor instead of http://localhost/appdir/vendor.
So I wonder, why? Is there something I am missing?
Thanks.

**Comment by b0rt** [comment]
sharp assumes it is being used in an installation directly inside webroot of a tld (not in a subfolder) the asset paths are generated with a beginning forward slash (/).. 

the webroot is configured in the webserver config e.g 

- apache vhosts directives
- nginx server block

you could try to tell your (local) server to rewrite any local file GET queries to include the subfolder part (/appdir) .. solution for apache would be something like this https://stackoverflow.com/questions/19483980/htacces-redirect-assets-to-assets-folder

The issue frequently arises in static website generators as well and here is a lengthy (aborted) discussion for nova (https://github.com/laravel/nova-issues/issues/471)

Or you could look at something like docker (https://laradock.io) or homestead  for your laravel development to better mimic deployment behaviour
 
This could be helpful if you're using XAMPP or something .. https://stackoverflow.com/questions/27268205/how-to-create-virtual-host-on-xampp

**Comment by vdf89** [comment]
Thank you very much, I solved by creating a virtual host.
