### ISSUE TITLE
At input form, how to do put a label that its value refresh?

### ISSUE THREAD

**Issue by eilopes** [code16/sharp#195]
I have a listbox with a value. Each time user selected an option that listbox, the label vale must be sum each value. Almost, reactive.

Some control?

**Comment by dvlpp** [comment]
There is nothing like this at the moment in Sharp. Maybe I can find some specific advice on a workaround if you elaborate your need?
(I'm closing this since it's not an issue, in the meantime, but I will follow the discussion on the closed issue)
