### ISSUE TITLE
Show dynamic data on a form

### ISSUE THREAD

**Issue by gramz** [code16/sharp#196]
Is it possible to display dynamic data on a form?
for example labels or another control to display: 1 failed  2 passed. 
And that these values ​​be updated if more data is added?

![WhatsApp Image 2019-10-26 at 09 22 21](https://user-images.githubusercontent.com/8531407/67623286-8fdef780-f7e0-11e9-8be9-4d074469be73.jpeg)

**Comment by dvlpp** [comment]
This status field is a `Select`, and its values would of course be declared as we wish (https://sharp.code16.fr/docs/guide/form-fields/select.html#configuration), but I think you are asking for front-side dynamic values (values added while the form is displayed): in this case, the only solution would be to use a remote datasource, like in an `Autocomplete`.
