### ISSUE TITLE
Entity list shows 404

### ISSUE THREAD

**Issue by cicrip** [code16/sharp#211]
I run sharp on Laravel Framework 5.8.35, followed exactly your spaceship example on https://sharp.code16.fr/docs/guide/building-entity-list.html#configure-the-entity. 
But when I enter the url after adding the entity to sharp-config:
 ```
 "spaceship" => [
            "list" => \App\Sharp\SpaceshipSharpList::class,
        ]
```
it throws a 404. 

Is there an issue with sharp and laravel 5.8.35. or is there something missing in the docs ?

**Comment by dvlpp** [comment]
First, there is no known issue with this particular version of Laravel—I used Sharp with this one.

I need much more information to understand your issue... Maybe you could first check Saturn's code and config, since the example you are following is from this project. The code is here: https://github.com/code16/sharp/tree/master/saturn, and you can try it by forking the package or directly here https://sharp.code16.fr/sharp/login (with admin@example.com / secret)

**Comment by cicrip** [comment]
Thank you for the Reply! 
I downloaded the complete Source from  https://github.com/code16/ then I steped in Saturn folder run 'composer install' migrated the database and run the seeder. 
When I run the Saturn app on its own folder with artisan now it redirects me to the docs folder in Sharp directory.  But I can't get it running on form the Sharp directory too. I'am really not new to laravel but I have no clue how to get it run It looks so easy In your documentation but quite equal what I do I get a 404.  Is there a starter package what is able to run out of the box ?

Small example ( Database is your sharp-saturn_dusk <http://localhost/phpmyadmin/db_structure.php?server=1&db=sharp-saturn_dusk>) : 

Login works: 



my sharp config: 



SpaseshipSharpList and SpaceshipPolicy is from your Saturn app : 





 but when I run http://localhost:8004/sharp/list/spaceship <http://localhost:8004/sharp/list/spaceship> it throws a 404 !



Any Idea? any hint?


Kind Regards

Tobi

**Comment by dvlpp** [comment]
Not sure about your specific problem, I can't see any of the embedded visuals you added, but one thing to start: I think you'll need to have a dedicated vhost in order to make saturn work (in my case, I use http://saturn.test/sharp). Maybe you can look to #187.

**Comment by dvlpp** [comment]
Closed because of inactivity
