### ISSUE TITLE
Problem with colors for states

### ISSUE THREAD

**Issue by emil-nasso** [code16/sharp#217]
Hi!
I am trying sharp out but I ran into a javascript issue with states.

![image](https://user-images.githubusercontent.com/1119706/71514329-686ae080-289e-11ea-94ef-a636d62991f4.png)

This is the lists configuration with the state defined.
```php
    public function buildListConfig()
    {
        $this->setInstanceIdAttribute('id')
            ->setSearchable()
            ->setDefaultSort('created_at', 'desc')
            ->setPaginated()
            ->setEntityState('published', PostPublishedState::class)
            ->setReorderable(new PostReorderHandler());
    }
```

Here is the `PostPublishedState:

```php
<?php

namespace App\Sharp;

use App\Post;
use Code16\Sharp\EntityList\Commands\EntityState;

class PostPublishedState extends EntityState
{
    /**
     * @return mixed
     */
    protected function buildStates()
    {
        $this->addState("1", "Published", self::PRIMARY_COLOR);
        $this->addState("0", "Draft", self::SECONDARY_COLOR);
    }

    protected function updateState($instanceId, $stateId)
    {
        Post::findOrFail($instanceId)->update(
            [
                'published' => $stateId,
            ]
        );

        return $this->refresh($instanceId);
    }
}

```

Can anyone provide me with any pointers as to where I can go from here? :)
Any more information i can provide?

**Comment by dvlpp** [comment]
Hi
I’m away from keyboard for a few days, but I think the issue is related to some data with a state value which is not allowed by your code (a value which is not 0 nor 1). I think, if this is it, that front code should be more permissive...

**Comment by dvlpp** [comment]
@emil-nasso did you have the chance to dig more on this issue?

**Comment by emil-nasso** [comment]
@dvlpp Not yet. I can probably look into it next week. Will be back with more info.

**Comment by emil-nasso** [comment]
@dvlpp I did some more digging here.

I have a "published"-field on my entitry. It is created as a "boolean" in laravel migrations but it really is stored as the strings "1" or "0".

The problem was a issue with types.

To test this out I added both string and int-representations of the states like this:

<img width="493" alt="PostPublishedState php — cards  SSH: docker ninjazombie se  2020-02-09 15-32-41" src="https://user-images.githubusercontent.com/1119706/74104065-707e9700-4b51-11ea-9b80-8f1a4a51be68.png">

When looking at the data in the ajax request you can clearly that only the int-versions of the states are published. For the model the field consists of strings. This is probably why the colors can't be mapped.

![https://dl.dropboxusercontent.com/s%2Fmzv7lm933gkf7pj%2FSharp%252C%2520Posts%2520%2520Sharp%25204.2.1%25202020-02-09%252015-25-36.png](https://dl.dropboxusercontent.com/s%2Fmzv7lm933gkf7pj%2FSharp%252C%2520Posts%2520%2520Sharp%25204.2.1%25202020-02-09%252015-25-36.png)

The problem seems to be that something converts the states from strings to ints.

I fixed the problem by casting the field on the eloquent model to ints like this:

```php
    protected $casts = [
        'published' => 'integer',
    ];
```
After that, everything worked as expected.

This was mostly done to demonstrate the problem. I will change the implementation to cast to bool instead as that makes more sense. :)

**Comment by emil-nasso** [comment]
Update. Boolean also didn't work. :) 

This:
<img width="507" alt="PostPublishedState php — cards  SSH: docker ninjazombie se  2020-02-09 15-40-04" src="https://user-images.githubusercontent.com/1119706/74104182-7cb72400-4b52-11ea-8ffa-6abd4fed1add.png">

Gets exposed as this:

<img width="767" alt="Sharp, Posts | Sharp 4 2 1 2020-02-09 15-40-59" src="https://user-images.githubusercontent.com/1119706/74104195-9bb5b600-4b52-11ea-97d9-8d8a1d08bee0.png">

I'll have to keep it as int for now and cast to int on the model.
