### ISSUE TITLE
Could you please give me more info on sharp?

### ISSUE THREAD

**Issue by FreddyCrugger** [code16/sharp#218]
Hello,

I am getting a bit lost, so many packages out there and each time you have to relearn everything.

I just tried backpack for Laravel and did not find it straight forward especially when it comes to table relations.
How can Sharp help a normal developer in everyday tasks versus backpack for example?
Can you use Laravel(6) and sharp together very easily?
Does sharp includes many cool gadgets to create form faster? It difficult to pass the data from one table to a dropdown menu in a CRUD for example?

Also, is sharp using Jquery, or vue or another library in the front end?

Do you have a CRUD generator inside it?

Thank you.

**Comment by dvlpp** [comment]
Hi,
Please refer to the documentation on https://sharp.code16.fr for all those details, and to Medium's many post ion the subject (https://medium.com/code16/tagged/sharp); feel free to post any issue here. 
Unfortunately, I do not have time nor resource to provide direct help or assistance... Sharp is an open source free package and this is an issue tracker, not a help desk.
