### ISSUE TITLE
how to modify the front-end code.

### ISSUE THREAD

**Issue by MaherSaleem** [code16/sharp#223]
Hey,
I'm using your package and it's awesome. 
but I need to do some modifications to the UI, is there a way to do that?

I just have the compiled/minified versions of front-end code in the vendor path, how can I get the original code and to modify it manually?

Thanks

**Comment by dvlpp** [comment]
You can try these possibilities to adjust details: https://sharp.code16.fr/docs/guide/style-visual-theme.html. But if you need more control, Sharp does not provide anything else... I guess you'd have to fork the repo and start from here.

**Comment by staniktomas** [comment]
This style injection is not working for Show layout.
