### ISSUE TITLE
"this.value is null" when trying to put a Markdown editor in list field

### ISSUE THREAD

**Issue by jefffairson** [code16/sharp#224]
Hello,

It seems that implementing a Markdown editor in a List Field is not working, each time I'm trying do put and editor I've got this message : `this.value is null`

Is it possible to do this ?

**Comment by dvlpp** [comment]
It's definitively possible. When does this error happen? At update? Could you share some stack trace / details?

**Comment by aguingand** [comment]
Will be fixed in v4.2.3
