### ISSUE TITLE
Font awesome upgrade ?

### ISSUE THREAD

**Issue by rycks** [code16/sharp#230]
I'm using fontawesome 5 for my project but sharp seems to embedded fa 4 (i think), so do you plan to upgrade to fontawesome 5 ? or any tip to do it by myself on my project ?

**Comment by rycks** [comment]
Here is a "solution" on my git fork (it works for me) ... but i know there is a lot of things to do for moving from font awesome 4 to 5 ... 

https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

**Comment by aguingand** [comment]
Shipped in 5.0
