### ISSUE TITLE
Problem with date form field

### ISSUE THREAD

**Issue by ZuzanaBasovska** [code16/sharp#236]
When creating the new item it works ok, but after changing date in update form, in data there is the date one day less than in date picker.

**Comment by jefffairson** [comment]
Hello, do you use Carbon ? Do you cast your date fields in models as Carbon ? Did you check if your Timezone is setup correctly ?
Maybe I'm wrong but it's more like a date problem management than an actual sharp issue.

**Comment by ZuzanaBasovska** [comment]
Yes, I have all of these, I don't think the problem is on my side.

**Comment by ZuzanaBasovska** [comment]
When I clear the field with x and then I choose the date, it works right. So temporary I have solved it with JS - on click the field is cleared and it works ok.

**Comment by dvlpp** [comment]
I can't figure out the issue... could you share the code of the Form and the Model?

**Comment by dvlpp** [comment]
[Closed for inactivity]
