### ISSUE TITLE
Another Question: Is it possible to fill fields in pivot tables ?

### ISSUE THREAD

**Issue by ewatch** [code16/sharp#238]
Hi,

I have two models which have a many to many relation.
I'd like to fill an additional column which exists in the pivot table.
Is it possible to create a form for one of these models where you can associate an existing other model including the attribute to the pivot table ?

Or am I thinking from the wrong direction ?

Thanks and best regards,
ewatch

**Comment by ewatch** [comment]
Hi again,

I think I found a solution:
by having either a Model or a Pivot class for the intermediate table and creating a 1:N relationship to that object (hasMany / belongsTo).
I used then this relationship to create the fields for the intermediate table.

If you have a better idea without having the pivot class please let me know.

Thanks and best regards,
ewatch

**Comment by dvlpp** [comment]
Well, N:N relations are automatically handed by `Code16\Sharp\Form\Eloquent\WithSharpFormEloquentUpdater` either with Tags field (https://sharp.code16.fr/docs/guide/form-fields/tags.html) or AutocompleteList field (https://sharp.code16.fr/docs/guide/form-fields/autocomplete-list.html); neither of them can handle additional columns in the pivot table, so you can:
- use your solution: add a Model for the pivot table, and define 1:N relationships;
- write some custom logic in the `update()` function of your form: add a field for this additional column, ignore it before passing the data to `save()`, and handle it manually after.

**Comment by ewatch** [comment]
Okay thanks.
By using the 1:N relationships I was able to have a SharpFormListField with two item fields being SharpFormAutocompleteField, SharpFormSelectField which perfectly save the correct values.

Thank you for your answer.
I think we can close this issue.
