### ISSUE TITLE
Date-DateTime-DateInterval and Range Filters

### ISSUE THREAD

**Issue by Insolita** [code16/sharp#24]
Is there simple way for create filters with date/datetime input or date interval (for select entities created between startDate - endDate) 
and also range filters for ex. for select entites with price between minPrice and maxPrice

**Comment by Insolita** [comment]
and also questions:
- what about choosable perPage filter; 
- ability for select visible columns
- bulk grid actions support

**Comment by dvlpp** [comment]
On range filters: at the moment, no, you can only do that manually: for instance, you may define range steps like "between €100 and €200".

A per page filter: well, you can do that if you want. Simple example:

    function getListData(EntityListQueryParams $params)
    {
        // Assuming you declare a filter named perPage
        return Post::paginate($params->filterFor("perPage"));
    }

Select visible columns: if you mean select them on the user side, you can't (you can only, in the code, choose to hide some in small screens). But you can choose to display or hide columns on the code side, depending on some configuration for instance: the list layout is code based.

Bulk grid actions: do you mean a Command on a group of instances? If so, it's possible, [as documented here](https://github.com/code16/sharp/blob/master/docs/commands.md) (entity commands) and [blogged here](https://medium.com/@lonchampt/about-sharp-for-laravel-part-5-44699e270647) ("And what if the whole team is sick?").

**Comment by Insolita** [comment]
> Bulk grid actions: do you mean a Command on a group of instances? If so, it's possible, as documented here (entity commands) and blogged here ("And what if the whole team is sick?").

hmm, seems that Commands supports multiple ids, but not clear how we can mark concrete ids, for examples - i have list with unupproved commands, and i want approve selected comments with id 1,2,5,8 
or i have list of users, and i want select some of its and pass selected ids to action that rendered form for send email notification with passed ids.

**Comment by Insolita** [comment]
> Select visible columns: if you mean select them on the user side
Yes, i mean  ability for user to choose displayed columns (it very useful for tables with many columns)

**Comment by dvlpp** [comment]
DateRange filters were added to the version 4.1.17.
