### ISSUE TITLE
Sorting by accessors?

### ISSUE THREAD

**Issue by dv5150** [code16/sharp#242]
Hello,

I have a listing of Employee records in Sharp 4.2.4. 

Employees have a birth_date timestamp field in db and the model itself has an accessor named 'getAgeAttribute' which returns the age of the actual Employee as an integer. 

I would like to display this value instead of the birth date timestamp, so far everything looks nice except when I try to sort (not talking about reordering!) the records by 'age' I get the mysql error 'column age not found' of course - that column doesn't exist physically.

Is there an easy way to set up the complete sorting logic on the Javascript side? I believe it would eliminate this problem once for all.

**Comment by dvlpp** [comment]
Hi,

Yes, in this case you'll have to handle this orderBy logic on your own. Here's some sudo code as an example:

```php
// in you EntityList class
function getListData(EntityListQueryParams $params)
{
    $employees = Employee::query();

    if($params->sortedBy() == "age") {
        $employees->orderBy("birth_date", $params->sortedDir());
    } else {
        $employees->orderBy($params->sortedBy(), $params->sortedDir());
    }
    [...]
}
```

Another solution, better in your case: register your column under the `birth_date` attribute, and add a custom transformer on the `find()` method for this attribute to return the formatted age ([example of transformer in Saturn](https://github.com/code16/sharp/blob/11348c78a0a0ebdd7768f5f080112c8b283f81df/saturn/app/Sharp/PassengerSharpList.php#L74)). In this case, no need to test the attribute when sorting, since Sharp will send `birth_date`.

**Comment by dv5150** [comment]
I also needed to sort 'age' in the opposite direction as I would sort 'birth_date' so with your help I came up with the following solution (code simplified to make it shorter):

```
class EmployeeList extends SharpEntityList
{
    const CUSTOM_SORT_FIELDS = [
        'age' => 'birth_date'
    ];

    const CUSTOM_SORT_DIRECTIONS = [
        'age' => 'inverted'
    ];

    public function buildListDataContainers()
    {
        $this->addDataContainer(
            EntityListDataContainer::make('age')->setLabel('Age')->setSortable()
        );
    }

    public function buildListLayout()
    {
        $this->addColumn('age', 2);
    }

    public function getListData(EntityListQueryParams $params)
    {
        $sortedBy = $this->replaceSortField($params->sortedBy());
        $sortedDir = $this->replaceSortDirection($params->sortedBy(), $params->sortedDir());

        $employees = $this->employeeRepository->with(['company'])
                                              ->orderBy($sortedBy, $sortedDir)
                                              ->paginate(25, [
                                                  'employees.birth_date',
                                              ]);

        return $this->transform($employees);
    }

    public function replaceSortField(string $field): string
    {
        return !array_key_exists($field, self::CUSTOM_SORT_FIELDS)
            ? $field
            : self::CUSTOM_SORT_FIELDS[$field];
    }

    public function replaceSortDirection(string $field, string $originalDirection): string
    {
        if (!array_key_exists($field, self::CUSTOM_SORT_DIRECTIONS)) {
            return $originalDirection;
        }

        if (self::CUSTOM_SORT_DIRECTIONS[$field] !== 'inverted') {
            return $originalDirection;
        }

        return $originalDirection === 'desc'
            ? 'asc'
            : 'desc';
    }
}
```

Thinking about making the last 2 methods as a trait aswell. Will look into your second solution with the transformers too.
