### ISSUE TITLE
Issue with ordering (sorting)

### ISSUE THREAD

**Issue by gansky-alexander** [code16/sharp#244]
Hello, guys!

I am trying to create a list with sorting and get next error.

I am using next code for this:
```
/**
     * Build list containers using ->addDataContainer()
     *
     * @return void
     */
    public function buildListDataContainers()
    {
        $this->addDataContainer(
            EntityListDataContainer::make('name')
                ->setLabel('Product name')
                ->setSortable()
                ->setHtml()
        )
...
/**
     * Build list config
     *
     * @return void
     */
    public function buildListConfig()
    {
        $this->setPaginated()
            ->setSearchable();
    }
```

When i open a list i get next issue and do not know how to fix it - 

> Order direction must be "asc" or "desc".

 Could you please help me with it?

**Comment by gansky-alexander** [comment]
When i write parameters for URL like next http://laravel.local/admin/list/product?**sort=name&dir=asc** i have not issue, but without a parameters

**Comment by dvlpp** [comment]
Hi; could you post your `getListData()` code (or better: link to a gist with the full EntityList code)?

**Comment by dvlpp** [comment]
Is there something new on this, @gansky-alexander?

**Comment by gansky-alexander** [comment]
Hello, @dvlpp !

I decided to use another project, so i do not have any updates regarding my issue. I will close current one. 

Thank you !
