### ISSUE TITLE
Add more html5-field types for SharpFormTextField

### ISSUE THREAD

**Issue by Insolita** [code16/sharp#25]
why only text and password types supported? 
What about email, url, tel, color?

**Comment by dvlpp** [comment]
Not at the moment, because we prefer to use validation, which is more flexible, for this. 

But I think this is easy to add in a specific project: just extend `Code16\Sharp\Form\Fields\SharpFormTextField`, overriding `make()` and `validationRules()`:

```
class EmailSharpFormTextField extends SharpFormTextField
{
    public static function make(string $key)
    {
        return new static($key, "email", new TextFormatter);
    }

    protected function validationRules()
    {
        return [
            "inputType" => "required|in:email",
        ];
    }
}
```
