### ISSUE TITLE
Upload inside a list field (form)

### ISSUE THREAD

**Issue by niccolofavari** [code16/sharp#253]
Hello,
I'm building a tool where the user can create multiple "client resources". Each client resource has its own properties and stores its data in the `client_resources` table. Also each resource may have a `Media` (hence the upload). I used the standard Sharp upload procedure (the regular Media table and the standard upload fields with no customizations)

![2020-06-19 18_11_39-Nativa - Backend, Clienti](https://user-images.githubusercontent.com/183181/85155957-b531e180-b259-11ea-9c94-0645f16d9a68.png)

It works during update and creation (the files are there! there's no error and I can query them via eloquent) but for some reason I cannot show the edit/remove box with preview once the file is uploaded.

![2020-06-19 18_11_05-Nativa - Backend, Clienti](https://user-images.githubusercontent.com/183181/85156053-d1ce1980-b259-11ea-9131-8c92c5cbb618.png)

I'm doing something wrong but I cannot figure out what. Maybe in the `find` function?

![2020-06-19 18_23_41-ClientSharpForm php - nativa - Visual Studio Code](https://user-images.githubusercontent.com/183181/85156294-2a051b80-b25a-11ea-9b9e-07720c52d19a.png)

I tried different syntaxes but I had no luck.

I'm open to any suggestion.
Thank you

**Comment by dvlpp** [comment]
Hi,
Maybe  looked at this a bit too quickly, but I think you have to add a `:` in your custom transformer for `resource_file`, since it's a relation. I mean:

```php
  $this->setCustomTransformer("client_resource:resource_file", ...)
```

**Comment by niccolofavari** [comment]
Thank you very much for the answer. I decided to split the screen of client_resources in their own forms (so now the upload works as usual) but I will get back to this particular issue and try your suggestion in the coming days (as this might happen again for other projects).
Thank you!

**Comment by dvlpp** [comment]
Closed (inactivity)
