### ISSUE TITLE
Interface 'Code16\Sharp\EntityList\EntityListSelectFilter' not found

### ISSUE THREAD

**Issue by mukhsin** [code16/sharp#255]
Hi,

I followed instruction here
https://sharp.code16.fr/docs/guide/filters.html#generator

But I got an error Interface 'Code16\Sharp\EntityList\EntityListSelectFilter' not found
What should I do to fix this?

Thanks

**Comment by dvlpp** [comment]
Hi,
Which version of sharp are you using?

**Comment by mukhsin** [comment]
I'm using ^4.2

**Comment by dvlpp** [comment]
Could you try to run `composer dump-autoload -o`, and see if the interface is now found?

**Comment by mukhsin** [comment]
It looks like this
![image](https://user-images.githubusercontent.com/9584947/87278770-71a45d80-c50f-11ea-9e3c-1fc4e4c74bdb.png)

Currently I'm using `SharpEntityList` as alternative instead of `EntityListSelectFilter ` and it's working

**Comment by OrkhanS** [comment]
Have you solved the issue? I am getting the same kind of error now.

**Comment by dvlpp** [comment]
Seems that's the autoloading can change its behavior (maybe related to php version) regarding to multiple interfaces defined in one file. We split those files in this version https://github.com/code16/sharp/releases/tag/v5.3.2, it should be fixed in all cases.

**Comment by adiletmaks** [comment]
this is because of composer version, you must use composer 1 with 4 verison package or upgrade package to 5
