### ISSUE TITLE
Ignore unique value on update not working properly for me

### ISSUE THREAD

**Issue by niccolofavari** [code16/sharp#256]
I'm having issues with updating rows in the DB using a unique rule with a FormRequest.

I followed the Sharp documentation (and the usual Laravel doc for FormRequest) but I couldn't get this to work properly.

I have a `SharpNumberField` field in the SharpForm for the `id`.
It's not shown in the layout but I added it to be able to access the `$id` property in the validator (is this passage correct?)

My FormRequest `rules()` is written as follows

```
public function rules()
{
        $validator = [
            'netname' => ['max:255'],
            'ip' => ['required', 'ipv4'],
            'zone_id' => ['required', 'exists:zones,id']
        ];
        
        // In case we're updating
        if ($this->id)
            $validator['name'] = ['required', 'max:255', "unique:devices,id,{$this->id}"];
        else
            $validator['name'] = ['required', 'max:255', "unique:devices"];

        return $validator;
}
```

This _works_ for creating new instances.
This _works_ for updating already existing instances (correctly ignoring their own name).

This does **NOT** work when changing name of an instance to another, already existing, instance's name.

I get the SQL error instead of the validator message.

Can you point me in the right direction?
Thank you,
Nick

**Comment by dvlpp** [comment]
Hi,

You should use the `Code16\Sharp\Http\ WithSharpContext` trait to get the current instance id (available in the update case). Here's an example:

```php
class SomeValidator extends FormRequest
{
    use WithSharpContext;

    public function rules()
    {
        return [
            'zone_id' => [
                'required',
                Rule::unique("zones", "id")
                    ->ignore($this->context()->instanceId())
            ],
            ...
        ];
    }
}
```

**Comment by kenniko** [comment]
Or without `use Illuminate\Validation\Rule;`

```
class SomeValidator extends SharpFormRequest
{
    use WithSharpContext;

    public function rules()
    {
        return [
            'zone_id' => [
                'required',
                $this->context()->instanceId() ? 'unique:table_name, zone_id,'.$this->context()->instanceId() : 'unique:table_name',
            ],
        ];
    }
}
```
