### ISSUE TITLE
Custom Show component

### ISSUE THREAD

**Issue by rpensek** [code16/sharp#262]
Hey I'm looking to create my own custom component for Show view. I followed the documentation and managed to set up Vue component, sharp-plugin, Custom Sharp Show Field and reference it in Show view. More info:

sharp-plugin.js
```
import Sharp from 'sharp-plugin';
import Gallery from './components/Gallery.vue';

Vue.use(Sharp, {
    customFields: {
        'custom-gallery': Gallery
    }
})

window.Vue.config.productionTip = false
window.Vue.config.devtools = true
```

Gallery.vue
```
<template>
    <div>
        Simple test: {{ value }}
    </div>
</template>

<script>
    export default {
        props: {
            value: String, // field value
        },
    }
</script>
```

SharpCustomShowFieldGallery.php
```
<?php

namespace App\Sharp\CustomFields;

use Code16\Sharp\Show\Fields\SharpShowField;

class SharpCustomShowFieldGallery extends SharpShowField
{
    const FIELD_TYPE = "custom-gallery";

    public static function make(string $key)
    {
        return new static($key, static::FIELD_TYPE);
    }

    public function toArray(): array
    {
        return parent::buildArray([]);
    }
}
```

ArticleShow.php
```
// inside buildShowFields()
$this->addField(
    SharpCustomShowFieldGallery::make("location")
);
// inside buildShowLayout()
$this->addSection('', function(ShowLayoutSection $section) {
     $section->addColumn(12, function(ShowLayoutColumn $column) {
          $column->withSingleField('location');
      });
});
```

I can see the component present in sharp-plugin.js and the JS is being called in the browser. In network tab I can see the `location` field in layout, fields and data objects in response. If I use Vue DevTools I can get to <SharpShowField> component with following computed props:

```
component:undefined
isVisible:false
props:Object
emptyVisible:false
key:"location"
type:"custom-gallery"
```

Any idea why it doesn't recognize my custom component? Am I missing something?

**Comment by aguingand** [comment]
The key must be `gallery` instead of `custom-gallery` in js plugin file:
```js
import Sharp from 'sharp-plugin';
import Gallery from './components/Gallery.vue';

Vue.use(Sharp, {
    customFields: {
        'gallery': Gallery
    }
})
```

**Comment by rpensek** [comment]
Hi @aguingand sorry, I forgot to mention I already tried that - basically that's what was set when I followed the documentation. Because it didn't work I tried other key names.
I've changed it back to `gallery` and still don't see the component listed - just an empty section. I can see that the change took effect in the mix output:

```
Vue.use(sharp_plugin__WEBPACK_IMPORTED_MODULE_0___default.a, {
  customFields: {
    'gallery': _components_Gallery_vue__WEBPACK_IMPORTED_MODULE_1__["default"]
  }
});
```

**Comment by aguingand** [comment]
I cannot reproduce with your code, if you can provide a full reproduction repo.

**Comment by rpensek** [comment]
@aguingand found out the culprit. It appears that when upgrading from v4 to v5 I was still using the old assets although it should update using composer `post-autoload-dump`. Running the command manually fixed the issue for me.
Thanks for the help and being responsive!
