### ISSUE TITLE
Update entity state return error

### ISSUE THREAD

**Issue by af-cl** [code16/sharp#277]
Hello,
In my EntityList, I declared the default sort (setDefaultSort ('position', 'asc')) in the function buildListConfig() , everything worked fine until I created the EntityState to change status, I get an error after updating. I checked it and in fact the variables are set to null.  I am using version 5.3.1

![Screenshot_2](https://user-images.githubusercontent.com/73356284/97033843-41377b00-1564-11eb-8337-f747fecc388f.png)

![Screenshot_1](https://user-images.githubusercontent.com/73356284/97032985-ecdfcb80-1562-11eb-8c0f-d6e5f50ac159.png)

To fix the error you have to overwrite the variables in the function  getListData() e.g.
`$sortedBy = (is_null($params->sortedBy())) ? 'position' : $params->sortedBy();`
`$sortedDir = (is_null($params->sortedDir())) ? 'asc' : $params->sortedDir();`
and passing them to the function orderBy `->orderBy($sortedBy, $sortedDir)`

**Update:** This does not work with pagination, the status is not reloaded automatically.

**Comment by dvlpp** [comment]
Hi,

EntitySates return (by default) a `refresh` action (https://sharp.code16.fr/docs/guide/entity-states.html#update-a-state). This means that Sharp tries to only reload the updated item, not the whole list; in this case, the query is not sent, and you have to handle this case in your `getListData()` method, checking for `params->specificIds()`: see https://sharp.code16.fr/docs/guide/commands.html#command-return-types.

You can also refer to this example in Saturn, the demo project (https://github.com/code16/sharp/blob/master/saturn/app/Sharp/PilotSharpList.php#L53-L90): 

```php
    function getListData(EntityListQueryParams $params)
    {
        $pilots = Pilot::select("pilots.*")->distinct();


        if($ids = $params->specificIds()) {
            $pilots->whereIn("id", $ids);


        } else {
            if ($spaceship = $params->filterFor("spaceship")) {
                $pilots->leftJoin("pilot_spaceship", "pilots.id", "=", "pilot_spaceship.pilot_id")
                    ->leftJoin("spaceships", "spaceships.id", "=", "pilot_spaceship.spaceship_id")
                    ->where("spaceships.id", $spaceship);
            }


            if ($role = $params->filterFor("role")) {
                $pilots->where("role", $role);
            }


            if ($params->sortedBy()) {
                $pilots->orderBy($params->sortedBy(), $params->sortedDir());
            }


            if ($params->hasSearch()) {
                foreach ($params->searchWords() as $word) {
                    $pilots->where('pilots.name', 'like', $word);
                }
            }
        }


        return $this
            ->setCustomTransformer("role", function($role, $pilot) {
                return $pilot->role == "sr" ? "senior" : "junior";
            })
            ->setCustomTransformer("xp", function($xp, $pilot) {
                return $pilot->role == "sr" ? $xp . "y" : null;
            })
            ->transform($pilots->paginate(30));
    }
```
