### ISSUE TITLE
Quick question for testing

### ISSUE THREAD

**Issue by jefffairson** [code16/sharp#280]
Hello there,

In a sharp form instance, I use sharp context to link certain content with the content I which to create like this 👍 
```
if ($breadcrumb = $this->context()->getPreviousPageFromBreadcrumb("show")) {
            list($type, $entityKey, $instanceId) = $breadcrumb;
            $this->page_id = $instanceId;
        }
```

When I test my code, I have troubles because in this particular case, page_id is not set, because it's set by the context.  
I did this to avoid that, but it's not very clean :
```
if ($breadcrumb = $this->context()->getPreviousPageFromBreadcrumb("show")) {
            list($type, $entityKey, $instanceId) = $breadcrumb;
            $this->page_id = $instanceId;
        }
if(config('app.env') === "testing") {
$this->page_id = 1;
}
```

So my question, is there a way to force Sharp context for testing purposes ?

**Comment by dvlpp** [comment]
I think this is not possible at the moment... We need to think about it — testing sharp functional code needs to be improved globally.

**Comment by jefffairson** [comment]
Hello @dvlpp 

In the meantime I dig further and tricked the system like this using the setup function : 
```
$this->get(
            route(
                'code16.sharp.show',
                [
                    'entityKey' => 'page',
                    'instanceId' => $this->page->id,
                ]
            )
        );
```
But then I had other issues testing the markdown editor content.  
Anyway, glad to hear you'll improve testing in the future ;)

**Comment by dvlpp** [comment]
This will be done in the coming version (Sharp 6), since breadcrumb / context was entirely rewritten.
