### ISSUE TITLE
How can I implement multi-upload?

### ISSUE THREAD

**Issue by mgzavri** [code16/sharp#295]
Even a simple replacing a **$this->morphOne** with a **$this->morphMany** in my Model leads to an error.  ))
What can I do to implement files multi-upload?
Thanks!

**Comment by dvlpp** [comment]
Hi! please report to dedicated documentation (https://sharp.code16.fr/docs/guide/sharp-built-in-solution-for-uploads.html#what-about-upload-lists) and/or to examples (https://github.com/code16/sharp/blob/e8a7c2b732558a05cbed42bb082cebeef3f424a0/saturn/app/Sharp/SpaceshipSharpForm.php#L189); if you encounter a specific bug, open an issue here with implementation details, error message, the version number you're on, ...

**Comment by mgzavri** [comment]
Thank you! How could I not see?! Sorry.
