### ISSUE TITLE
Allow downloads form Iframe

### ISSUE THREAD

**Issue by gramz** [code16/sharp#296]
Hi. 
I am trying to download from a view displayed in an modal iframe with a command returning a view action. 

But it gives me the following error: download of xxx was blocked because the triggering iframe has the sandbox flag set.

Checking in the inspector, I see that the iframe code shows me:
`<iframe` src="about:blank" sandbox="allow-forms allow-scripts allow-same-origin allow-popups"></iframe>`

Looking for the error, I found that the iframe needs to have the allow-donwloads flag

So adding manually the allow-dowloads flag from the browser inspector,  then it allows me to download.

Is it possible to send this flag as a parameter to the iframe?

**Comment by aguingand** [comment]
Released in [v5.4.4](https://github.com/code16/sharp/releases/tag/v5.4.4)
