### ISSUE TITLE
Incorrect request building for entityCommand for EntityListMultipleFilter

### ISSUE THREAD

**Issue by Insolita** [code16/sharp#30]
**Description:**
Error occured in https://github.com/code16/sharp/blob/master/src/EntityList/EntityListQueryParams.php#L183
Because request data for multiple filter parameter contains array of values instead of comma separated values like for list
Seems this place https://github.com/code16/sharp/blob/master/src/EntityList/EntityListQueryParams.php#L77
is bug source, because for EntityList request fetched via `request()->all()`  but for EntityCommand request fetched via `request("query")`  and it needs to prepare in valid format

**Steps for reproduce**

1. Make any filter implemented EntityListMultipleFilter and attach it to some SharpEntitlyList 
2. Make EntityCommand with usage `$params->filterFor("multifilter_name")` and attach it to the SharpEntitlyList 
example 

```php
class ReadMarkAll extends EntityCommand
{
   ...
    public function execute(EntityListQueryParams $params, array $data = []): array
    {
        $models = Model::orderBy($params->sortedBy() ?? 'created_at', $params->sortedDir() ?? 'desc');
        if (!empty($params->filterFor("level"))) {
            $models->whereIn("level", Arr::wrap($params->filterFor("level")));
        }
        ...
        $models->update(['is_read' => true]);
        return $this->reload();
    }
}
```
3. Try to execute entity command and got error

> mb_strpos() expects parameter 1 to be string, array given 

I can make PR with fix, but not sure in best way. As first, we can to make additional query formatting when $queryPerfix not null, in other way, we can to add filter value formatting in setFilterValue method https://github.com/code16/sharp/blob/master/src/EntityList/EntityListQueryParams.php#L211
But may be it require fixes on client-side

**Comment by dvlpp** [comment]
Thanks, I applied your proposal, for consistency in request types. I'll have to work on JS code too, I saw a related bug there, but you patch is working as expected.
