### ISSUE TITLE
Subgroups in menu

### ISSUE THREAD

**Issue by AndrewRadchenko** [code16/sharp#318]
Current release allows to combine entities into groups in menu. It could be a good to allow subgroups.

**Comment by dvlpp** [comment]
Hi,

We tried in the past a more hierarchical menu, but it we thought it was messy: the idea is to keep this menu simple, to avoid complexity for the user.

We recently (6.1.0) added separators (https://sharp.code16.fr/docs/guide/building-menu.html#add-separators-in-categories) to handle more complex cases.

![](https://cdn.discordapp.com/attachments/833955910380158996/834310710208495646/Capture_decran_2021-04-21_a_08.06.07.png)
