### ISSUE TITLE
Documentation Entity List URL is not correct

### ISSUE THREAD

**Issue by tushargugnani** [code16/sharp#319]
Just discovered this package and realized that wrong URL is mentioned in the documentation /docs/guide/building-entity-list.html#buildlistconfig
Then we can access the Entity List at the following URL: /sharp/list/spaceship (replace "spaceship" by our entity key). 

Correct URL should be /sharp/s-list/spaceship. I figured out after spending some time on why I was getting 404 even after creating the entity list.

**Comment by aguingand** [comment]
Fixed, thanks!
