### ISSUE TITLE
Commands on Entity with no instances (empty table)

### ISSUE THREAD

**Issue by AndrewRadchenko** [code16/sharp#322]
Is there a way to add command like "new" that is available with no reference to number of records (available in empty database).
If there is a way, how to add and how to configure this commands to different entities?
![Снимок экрана 2021-06-06 в 18 32 13](https://user-images.githubusercontent.com/22329845/120930678-0222f800-c6f7-11eb-9451-18aaf87873e8.jpg)
![Снимок экрана 2021-06-06 в 18 27 27](https://user-images.githubusercontent.com/22329845/120930681-03542500-c6f7-11eb-8a43-5e4a75e24bd2.jpg)

**Comment by dvlpp** [comment]
For your first question, check primary commands (https://sharp.code16.fr/docs/guide/commands.html#define-an-entity-command-as-primary).
For the second, if I understood well, you can associate a command to many entities if you want.
