### ISSUE TITLE
Show a Form field only if a FormCheck is selected or FormSelect Option is Selected 

### ISSUE THREAD

**Issue by IlyasDiker** [code16/sharp#327]
I would love to show a form field only if a Form Select Option is Selected

example :
isDisabled: ['No', 'Physical' , 'Mental', 'Mixte', 'Other']
Specifiy More : 'String' (Specify More field show only if 'Other' is selected)

**Comment by dvlpp** [comment]
This is called "conditional display": https://sharp.code16.fr/docs/guide/building-entity-form.html#conditional-display
