### ISSUE TITLE
SharpEntityList: align right not work for addColumnLarge

### ISSUE THREAD

**Issue by anigroSIS** [code16/sharp#328]
in buildLidtLayout()
`->addColumnLarge('coin_value', 1)`

in getListData()
`->setCustomTransformer('coin_value', function($value, $row) {
            $value = number_format(round($row['coin_value'], 2), 2, '.', '');
            return '<div style="text-align:right">'.$value.'</div>';
        })`

**Comment by dvlpp** [comment]
Could you use code format in the issue to make it readable and to allow HTML to be displayed (the div is missing).
And please also add the generated HTML (formatted) + the version of Sharp used.

**Comment by anigroSIS** [comment]
![immagine](https://user-images.githubusercontent.com/75420936/122718733-9354ab80-d26d-11eb-99e2-647a363f75bc.png)
![immagine](https://user-images.githubusercontent.com/75420936/122718511-538dc400-d26d-11eb-8cd1-1810268322a5.png)

**Comment by anigroSIS** [comment]
"code16/sharp": "^6.3"

**Comment by aguingand** [comment]
Will be fixed in v6.3.2

**Comment by anigroSIS** [comment]
I tried, via composer, versions 6.3.2 and 6.3.3 but your modification there aren't.

**Comment by anigroSIS** [comment]
name     : code16/sharp
descrip. : Let's call it a Laravel Content Management Framework
keywords :
versions : * v6.3.2
type     : library
homepage :
source   : [git] https://github.com/code16/sharp.git 25b63b853ab0a90fd63693b8851552d07649626e
dist     : [zip] https://api.github.com/repos/code16/sharp/zipball/25b63b853ab0a90fd63693b8851552d07649626e 25b63b853ab0a90fd63693b8851552d07649626e

**Comment by aguingand** [comment]
Sorry wrong version, it will be fixed soon in 6.3.4
