### ISSUE TITLE
Turbolinks support to smooth page transitions

### ISSUE THREAD

**Issue by fishnux** [code16/sharp#329]
Hi,

So, Sharp's page transitions are not smooth in the sense they don't look like an SPA application. When you change pages there's a small amount of time the page goes blank, a loading spinning indicator appears and only then the page is presented.

I propose the use of Turbolinks as a workaround to make page transitions smoother:
https://github.com/turbolinks/turbolinks

We would just need to include Turbolink's JS to get the benefit. The problem is, it seems to reload vendor.js and it errors the webpage. Probably we need to include a defer attribute to the <script> tags near < /body> to make it play nice. 

I don't have Sharp installed*, would appreciate if someone would be kind to add those defer attributes and inject Turbolink's script to see if it works :)

\* I tested Turbolinks by injecting it through DevTools, for reference:
```
javascript:void((function(){var e=document.createElement('script');e.setAttribute('src','https://cdn.jsdelivr.net/npm/turbolinks@5.2.0/dist/turbolinks.min.js');document.body.appendChild(e)})());console.log('Turbolinks.js loaded.');
```

**Comment by aguingand** [comment]
Thanks for the proposal, but Turbolinks would be a bit complicated to add because we use Vue + Vue router under the hood. However we will improve the loading overlay in a next release. Stay tuned!
