### ISSUE TITLE
Custom message & redirect after save/update

### ISSUE THREAD

**Issue by mdcass** [code16/sharp#33]
Hi,

Is there any elegant way to define a custom message which when flashed to the session (or similar) will display on the resulting page.

The scenario is to provide additional information after the creation of an entity. It might be useful to specify the redirect path after creating/updating too.

**Comment by mdcass** [comment]
> This is more problematic, to me, since routing is Sharp's business: after a Form, we go back to the List (keeping previous querystring)... What's your need / issue there?

My personal experience of web applications is that a store or update would redirect to the created/updated resource; seems like a pattern a majority of apps I have used in the past. It may be that developers share this need too, but not a hard requirement.

**Comment by dvlpp** [comment]
Yes, but there is no « show » page in Sharp... only Lists and Forms.

**Comment by mdcass** [comment]
Yes sorry, I mean redirect to the created/updated resource's Form

**Comment by dvlpp** [comment]
A little update on this: we are working on alerts, I think we'll be able to push something by the end of the week.

**Comment by dvlpp** [comment]
Notifications are implemented in v4.0.10, [as documented here](https://github.com/code16/sharp/blob/master/docs/building-entity-form.md#display-notifications)

This release also add [support for custom form fields](https://github.com/code16/sharp/blob/master/docs/custom-form-fields.md), thanks to @aguingand.
