### ISSUE TITLE
Using sharp show with pivot

### ISSUE THREAD

**Issue by jefffairson** [code16/sharp#330]
Hello,

Quick question, I would like to use a show for a Many to Many relationship with pivot table.
To filter the values, I tried this which does not seems to work, any thoughts ?
```
SharpShowEntityListField::make("criteres", "critere")
    ->hideFilterWithValue(
        "pivot.form_id",
        function ($instanceId) {
            return $instanceId;
         }
)
```

Cheers

**Comment by dvlpp** [comment]
Mmm, `pivot.form_id` should be a filter in the "critere" EntityList, I think this has nothing to do with relationships... See https://sharp.code16.fr/docs/guide/building-entity-show.html#embedding-an-entity-list-in-a-show

**Comment by jefffairson** [comment]
Yes ! It worked, I was doing it the wrong way. Thanks for your help, I will close the issue.
