### ISSUE TITLE
Display SharpEntityList or SharpForm in tab of SharpForm for hasOne and hasMany relationships

### ISSUE THREAD

**Issue by mdcass** [code16/sharp#34]
# Use Cases

* I have a `User` with a `hasOne` relation to a `Profile` model - it would be useful to be able to display the `SharpForm` for the profile in a tab on the `User`'s `SharpForm` and have it `POST` to the `Profile`'s `SharpForm`
* I have a `User` with a `hasMany` relation to a `SocialAuthentication` model it would be useful to be able to display the `SharpEntityList` filtered by the `user_id` for the `SocialAuthentication` model in a tab

## Implementation Notes

I'm unsure at this point whether this would require major changes, especially on the front-end, or whether it would actually be fairly easy.

I envisage the closure passed to the `addTab` method on the `SharpForm` class called from the `buildFormLayout` would return either a `SharpForm` class or `SharpEntityList` class, both accepting `parameters` which define in the first case, the instance being updated, and in the second case, the parameters to apply to existing filters on the `SharpEntityList`

**Comment by dvlpp** [comment]
You mean being able to open the full Form of a Profile from the User's Form, in a tab, and have 2 Forms opened at once, with 2 endpoints?

**Comment by dvlpp** [comment]
Mmm, that's not how it's meant to be used: tabs are useful to cut long forms, and are essentially just a way to group data with some logic, it's a layout trick — but the Sharp Form rule stays: one button to update all.

In your 1st case, `User` and `Profile`, I can think of some solutions:

1. obviously, each one can be its own entity; and if one is responsible for creating the other, it's easy with policies to prevent direct creation and/or deletion for one of them. I've done it quite often.
2. or is `Profile` and `User` are very close, you can merge them in one form, one endpoint, one entity. You can got for an entity based on the `User`, and having a `User::profile()` relationship add form fields like this:

````php
function buildFormFields()
{
    $this->addField(
        SharpFormTextField::make("profile:client_number")
                ->setLabel("Number");
}
````

This will work out of the box.

3. If thing are more complex, you can always handle the separation in the `update()` function, as you are free to do whatever you want there. For instance, say you have many fields for the `User` and, for the `Profile`, only `client_number` and `subscription_date`:

````php
function update($id, array $data)
{
    $instance = $id ? User::findOrFail($id) : new User;

    $this->ignore(["client_number", "subscription_date"])
             ->save($instance, $data);

    // Perform the login to update the profile here

    return $instance->id;
}
````

Your 2nd case seems even more easy: I *think*, if I understood well, that you have some relation `$user->socialAuthentication()` that returns a `HasMany`: you can build without specific code a `SharpFormListField` with this relation, and allow or not to add, remove, sort or update items there — in a new tab if you want to, no issue. Updating the user will imply updating this relation, too.
