### ISSUE TITLE
how could i use "deleteFileAfterSend" in EntityCommand ?

### ISSUE THREAD

**Issue by rycks** [code16/sharp#340]
Hello all,
i would like to delete the file just after download, like in laravel 
`return response()->download($pathToFile)->deleteFileAfterSend(true);`

https://laravel.com/docs/5.0/responses#other-responses

But i don't know how to do that ... could you help me please ?

**Comment by dvlpp** [comment]
Hi,
At the moment you can't do that, in Sharp... Or you'll need to involve a delayed queue job, or a maybe a daily cron.
