### ISSUE TITLE
Question on instance command

### ISSUE THREAD

**Issue by jefffairson** [code16/sharp#342]
Hello,

For a project I have to download a PDF generated on the fly, It will never be saved on the server.
On my instance command I wrote this ro try (don't take care of the apparent mess, it will be clean) :
```
public function execute($instanceId, array $data = []): array
    {
        $coaching = Coaching::findOrFail($instanceId);

        $pdf = PDF::loadView('pdf.coaching', ['coaching' => $coaching]);
        $pdf->output();
        $dom_pdf = $pdf->getDomPDF();
        $canvas = $dom_pdf ->get_canvas();
        $canvas->page_text(18, 18, "Page {PAGE_NUM} sur {PAGE_COUNT}", null, 7, array(0, 0, 0));
        return $pdf->stream();
    }
```

The trouble is with the return, in that case I've got a return type error which is totally normal.
I tried to replace the last line by ```return $this->download($pdf->stream())``` which then throw an error ```path not found```

Any advice for me ?

Thanks

**Comment by dvlpp** [comment]
As it was mentioned here #340, there is no direct solution to this issue at the moment.
I will take this into account for the next version, since it seems to be a common request...

**Comment by jefffairson** [comment]
Ah ok, didn't see this specific issue. Thx

**Comment by jefffairson** [comment]
Ok, I finally had an idea.  
On a previous project made with Sharp, I put export links on the Dashboard.  
The thing I did, is to put my logic in a specific controller method and build the export link with a custom transformer. It's not in the "actions" dropdown but it does the job !  
If someone have the same issue, it might do the trick.
