### ISSUE TITLE
Logout CSRF

### ISSUE THREAD

**Issue by HDVinnie** [code16/sharp#362]
https://huntr.dev/bounties/de0639c1-e4fa-43e8-94a1-b9aa75935a89/

**Comment by aguingand** [comment]
Fixed in 7.0

**Comment by HDVinnie** [comment]
@aguingand are you going to mark it valid on huntr then too?

**Comment by JamieSlome** [comment]
@aguingand - just to check, was the report provided above valid regarding this security issue?

**Comment by dvlpp** [comment]
... leading to potential annoyances like sending a link to someone with the logout URL hidden in a link.

**Comment by JamieSlome** [comment]
@aguingand - thanks for the information. Can you confirm the commit SHA that addresses this issue?

**Comment by aguingand** [comment]
@JamieSlome fixed in this PR https://github.com/code16/sharp/pull/364

**Comment by JamieSlome** [comment]
@aguingand - would you kindly consider marking the researcher's report as valid, and confirming the fix, so @HDVinnie can get their bounty? 🤝 

https://huntr.dev/bounties/de0639c1-e4fa-43e8-94a1-b9aa75935a89/

**Comment by dvlpp** [comment]
done ✔️

**Comment by JamieSlome** [comment]
@dvlpp - appreciate your support! ❤️
