### ISSUE TITLE
Problem with version 7.0.1 - Target class [Code16\Sharp\View\Components\Title] does not exist

### ISSUE THREAD

**Issue by anardil** [code16/sharp#363]
Hello,

I'm new with Sharp. It looks like a great framework :)
I decided to install the next version 7.0.1. and when I go the url /sharp/, I've go this error:

```
Illuminate\Contracts\Container\BindingResolutionException
Target class [Code16\Sharp\View\Components\Title] does not exist. (View: /Applications/MAMP/htdocs/sharp/vendor/code16/sharp/resources/views/layout.blade.php) 
```

How can I resolve this problem, please?
Thank you.

Regards.

**Comment by aguingand** [comment]
It should be solved by doing `php artisan view:clear`, it will be highlighted in migration guide

**Comment by anardil** [comment]
Thanks a lot. It works now.
