### ISSUE TITLE
XHR error on singleshow ? (trailing slash)

### ISSUE THREAD

**Issue by rycks** [code16/sharp#366]
Hello all,
i've got a problem with singleshow (sharp upgraded to 6.5.4 for this tests).

Here is a request on a list without problem:

![image](https://user-images.githubusercontent.com/1468823/145647927-016b0218-dbd9-44bb-9cb7-cabc833ea3a9.png)

But on single show entity like account there is a redirect "move permanently". Note that there is a trailing slash at the end of the uri ...

![image](https://user-images.githubusercontent.com/1468823/145648364-623cb06e-1229-4a00-ac52-a65b3b198b0a.png)

That "bug" (if it is) appears only on race conditions (hosting of laravel app behind a traefik frontal service).

Thanks
Éric

**Comment by rycks** [comment]
And some more data about that:

![image](https://user-images.githubusercontent.com/1468823/145649867-949713d8-0fa8-4b19-92e7-a7f568e53610.png)

If i use firefox dev tools to replay that request and i just remove the trailing slash

![image](https://user-images.githubusercontent.com/1468823/145649951-2f18f197-0d2c-4a9d-add5-5cdcf2a165b3.png)

**Comment by dvlpp** [comment]
@rycks did you manage to find a solution for this (see previous comment)?

**Comment by dvlpp** [comment]
closed (inactivity)

**Comment by jmuseyibli** [comment]
Hi @dvlpp, I am experience the same issue. It is https/http mixed content issue and the `APP_ENV` is correct. Anything I could try?
Env is `production` and https schema is forced on `AppServiceProvider`.

<img width="1507" alt="Screen Shot 2022-04-26 at 01 24 56" src="https://user-images.githubusercontent.com/29117759/165177581-aa38499d-74f0-4b79-abe9-02eef9d51f2d.png">

**Comment by dvlpp** [comment]
This 301 is strange; the `/public` part added to the response location URL would make me look at nginx / apache configuration (regarding your public root).
