### ISSUE TITLE
Pass data / parameters to a SingleShow Page

### ISSUE THREAD

**Issue by uwascan** [code16/sharp#368]
Is it possible to pass data / parameters to a ```SingleShow``` Page using ```LinkToSingleShowPage``` and ```LinkToSingleForm```?

**Comment by dvlpp** [comment]
Mmm, I'm not sure I understand: what would be the use case, since there is no filter, sort, search... on a show page?

**Comment by uwascan** [comment]
I think I can use ```Code16\Sharp\Show\SharpShow;``` for that instead. Still learning the ropes.

**Comment by dvlpp** [comment]
I'm confused. Please post here something specific, and maybe try Discord for help instead of issues. I'm closing this but feel free to reopen it in case of an actual bug / problem
