### ISSUE TITLE
Upload files to not a local disk

### ISSUE THREAD

**Issue by Petrov-Dmitry** [code16/sharp#426]
I ran into a problem when trying to save files to s3. Through research I found that here https://github.com/code16/sharp/blob/main/src/Form/Fields/Formatters/UploadFormatter.php#L71. You have hardcoded the value "local" instead of use value from $ field->storageDisk()

**Comment by dvlpp** [comment]
Yes, at the moment I think Sharp will force you to use the local filesystem for the upload folder, which is the tmp dir. You can of course define a custom filesystem for final storage, but the tmp dire must be local.

**Comment by Petrov-Dmitry** [comment]
But why? It's so sad that we need override this in our code...

**Comment by dvlpp** [comment]
This feature will be addresses in the upcoming version 8 of Sharp.

**Comment by dvlpp** [comment]
This is fixed in version 8
