### ISSUE TITLE
Tabs in show page layout

### ISSUE THREAD

**Issue by marcinlawnik** [code16/sharp#429]
`buildShowLayout(ShowLayout $showLayout): void` does not support tabs like the `buildFormLayout(FormLayout $formLayout)`.

With some of the models growing more complex, a need to tabulate the show has arisen to simplify navigation for the user.

**Comment by dvlpp** [comment]
Mmm, this is not in our plans to bring tabs to show pages: we already have sections, and even collapsable sections, to handle large entities (and we have some of them!). We try to keep things simple here.
