### ISSUE TITLE
Dynamic Vite generated CSS import

### ISSUE THREAD

**Issue by jefffairson** [code16/sharp#447]
Hello there,

For a project, I build my assets with Vite.
In the config I can place my file which is great, but I have en error building config if I do this : 
```
$specificSharpAsset = (new Vite())->asset('resources/sass/sharp.scss');
return [
  "extensions" => [
        "assets" => [
            "strategy" => "asset",
            "head" => [
                $specificSharpAsset,
            ],
        ]
    ],
];
```

When digging to find a solution, I found out that it's the asset function that's causing the issue.
Have you got a clean solution which can suits my needs ?

**Comment by aguingand** [comment]
Released in v7.26.0
