### ISSUE TITLE
Full dynamic configuration

### ISSUE THREAD

**Issue by jefffairson** [code16/sharp#448]
Hello again,

I've got a project which share the same code base for 2 different clients that I can set in my env file.
They have access to different entities lists so I wondered if I could load sharp config dynamically for each one ?
I tried this which is working, but I wondered if you got something cleaner ? 

```
if (config('platform')=== "LOLILOL") {
    $entities = [
        "particulier" => \App\Sharp\Entities\Particulier::class,
        "professionnel" => \App\Sharp\Entities\Professionnel::class,
    ];
}
return [
  'entities' => $entities,
];
```

**Comment by dvlpp** [comment]
Mmm, it seems that Sharp 7.19.0 can help here, see release notes: https://github.com/code16/sharp/releases/tag/v7.19.0

And [from the doc](https://sharp.code16.fr/docs/guide/#configuration):
> Instead of directly declaring an array of entities in the config file, you can type the full path of a class that implements the Code16\Sharp\Utils\Entities\SharpEntityResolver interface, and define here a public function entityClassName(string $entityKey): ?string method.

Is that what you were looking for?
(this feature is still in beta — there are performance issues — but we should fix this in the coming version, without BC)

**Comment by jefffairson** [comment]
Hello,
Not implemented yet, but after reading the documentation, it should totally do it ! 
Thx a lot.
