### ISSUE TITLE
Enhancement with (Model-Wizard, Policy Generator, and Entity Generator) Commands

### ISSUE THREAD

**Issue by IlyasDiker** [code16/sharp#463]
The proposed enhancement involves adding three new commands to the library: 
- Model-Wizard, `sharp:model-wizard --model=[Model]`
- Policy Generator, `sharp:make:policy`
- Entity Generator, `sharp:make:entity --model=[Model]`

**Comment by dvlpp** [comment]
This should be only in a PR https://github.com/code16/sharp/pull/464
