### ISSUE TITLE
Login form is using HTTP instead of HTTPS

### ISSUE THREAD

**Issue by sandervankasteel** [code16/sharp#480]
Hi there,

I am using a bit of a non-standard setup, so here goes nothing. Recently I've added Sharp to one of my Laravel projects and I am running into a slight inconvenience. Which is the login form from Sharp is using HTTP instead of HTTPS. Which causes some browsers (primarily Firefox on desktop and Chrome on Mobile) to show warnings that the data isn't transmitted securely. 

So my current setup is as follows;

```
INTERNET <--- HTTPS ---> Traefik <--- HTTP ---> Docker container with PHP-FPM + Nginx
```

HTTP to HTTPS redirection is setup and is currently being done by Traefik.

What I've already done is set the `APP_URL` to use `https` but unfortunately that doesn't resolve the issue. The `ASSET_URL` is also set to use `https`. When I call `route("code16.sharp.login.post")` in Tinker, I do get an HTTPS url back. 

```
/app # php artisan tinker
Psy Shell v0.11.16 (PHP 8.2.6 — cli) by Justin Hileman
> route("code16.sharp.login.post")
= "https://example.com/admin/login"
```

Any suggestions on what I can do to get the login form to POST to an HTTPS url instead of HTTP ?

**Comment by smknstd** [comment]
Hi @sandervankasteel,

First, I'm not familiar with your traefik setup.

When you say:

> the login form from Sharp is using HTTP instead of HTTPS

What do you mean ? What is in your browser address bar ?

Here are "normal login" requests:

![Uploading Screenshot from 2023-06-08 11-49-49.png…]()

Which one are you talking about ?

**Comment by sandervankasteel** [comment]
Sorry if I wasn't clear but the `action` attribute in the login from for Sharp is always using HTTP instead of HTTPS. This line in the login form to be exact https://github.com/code16/sharp/blob/main/resources/views/login.blade.php#LL8C52-L8C52.

I just did an extra check and ALL the URLs Sharp generate are HTTP instead of the expected HTTPS.  

The rest of the website is setup to use HTTPS, so I find this behavior a bit weird. :sweat_smile:

**Comment by dvlpp** [comment]
To me this is 100% related to `config('app.url')`, Sharp URLs are generated in the very same way that all other URLs of the project (as a package).

I suspect something weird linked to your configuration...

**Comment by sandervankasteel** [comment]
> To me this is 100% related to `config('app.url')`, Sharp URLs are generated in the very same way that all other URLs of the project (as a package).
> 
> I suspect something weird linked to your configuration...

Yeah that's what I am thinking as well... But the weird thing is, when I manually call `route('code16.sharp.login.post')`, it will return the expected HTTPS URL since my `APP_URL` is setup to use HTTPS. 

``` 
/app # php artisan tinker
Psy Shell v0.11.16 (PHP 8.2.6 — cli) by Justin Hileman
> route("code16.sharp.login.post")
= "https://example.com/admin/login"
```

But no matter the amount of cache clearing I do, it always seems to return a HTTP URL.

**Comment by dvlpp** [comment]
Mmm, double check your nginx and Traefik config for routing, this is the main diff to me between a browser and a tinker check. Since it really seems that it has nothing to do with sharp, I'm going to close this issue, but of course feel free to re-open it if you have new suspicions.
