### ISSUE TITLE
Vite assets not loading

### ISSUE THREAD

**Issue by IlyasDiker** [code16/sharp#490]
Using Sharp 8.0.2
The issue is mainly the vite assets are not loading
- vendors.scss
- app.scss
- client-api.js
- sharp.js

![image](https://github.com/code16/sharp/assets/28260951/de2d7767-17a2-4694-b837-bd1de00e5cdd)

Here what's inside my vite config

```
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import vue from '@vitejs/plugin-vue'

export default defineConfig({
    plugins: [
        vue(),
        laravel({
            input: ['resources/css/app.css', 'resources/js/app.js', 'resources/js/sharp-plugin.js'],
            refresh: true,
        }),
    ],
});
```
i've tried removing the `hot` file on the public  folder and the assets loaded.
but after i get an infite reloading issue 
![image](https://github.com/code16/sharp/assets/28260951/fa9d8807-a1fe-4df7-a211-603308bce315)

**Comment by aguingand** [comment]
Thank you, a fix has been released in v8.0.3.
