### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by nicolastorgato** [code16/sharp#495]
Hi,

I'm trying to use the latest version of Sharp. Currently I have PHP 8.2 installed on my PC using Laragon.

Problem: when I install a Laravel project, the PHP version in composer.json is: ` "php": "^8.1" `, and not 8.2. Is this normal? Why is that?

After installing Sharp (version 8.0), I noticed that I don't have the sticky menu top bar, but just the left one. I don't know if this has to do with dependency versions. Can you help me?

Thanks!

**Comment by dvlpp** [comment]
yes, `^8.1` allows 8.2 (see https://getcomposer.org/doc/articles/versions.md#caret-version-range-)
As for the sticky menu bar, it's odd, it should be fixed. Did you manage to find the origin of the problem?

**Comment by nicolastorgato** [comment]
Well, I've recently tried again and now it works correctly. Thanks!
