### ISSUE TITLE
Target class [sharp_invalidate_cache] does not exist.

### ISSUE THREAD

**Issue by jefffairson** [code16/sharp#505]
Hello there,

This is driving absolutely nuts !

I upgraded 2 projects from sharp 7 to sharp 8, one is working perfectly and the other one is throwing this error :
```Target class [sharp_invalidate_cache] does not exist.``` 

I tried 20 different thing before writing this issue such as :
 - remove completely the vendor folder and do a new composer install
 - deactivate all my custom middlewares
 - clearing all three folders config / view / cache
 - check the sharp config

Each time, I really took care of clearing the cache (just in case) and I'm still stuck with this error.

Did you encounter this already ? Is there something I forgot to check ?

Thanks for your help,
JF

**Comment by dvlpp** [comment]
Mmm, check your `sharp.middleware` config, It should [look like this](https://github.com/code16/sharp/blob/bd276d0d25b98eb7382053b28fa81b8c124b8c7f/config/config.php#L51-L68) (or be entirely missing).

Or maybe (even more plausible) you need to clear your route cache?

**Comment by jefffairson** [comment]
Ok, n00b time
I clear all the caches, but not the 'route' cache which caused this issue.
Maybe it would be relevant to put this in the documentation, just in case.
