### ISSUE TITLE
$props is undefined when added a custom form field

### ISSUE THREAD

**Issue by sandervankasteel** [code16/sharp#508]
Hi,

I've been trying to get add a custom form field to my Sharp setup by using the guide on the website (https://sharp.code16.fr/docs/guide/custom-form-fields.html). But no matter what I've tried, my console only seems to show an error saying `TypeError: $props is undefined`

![image](https://github.com/code16/sharp/assets/17492906/f2378fb1-fcdc-4bac-918f-7eb3aaeeb541)

I followed everything from the guide, but now matter what I try, I keep getting the same error.

What I've also tried to do is create a standard component which doesn't need any props or accepts any data input:

```js
<template>
    <div>
		<h1>This is a test component</h1>
    </div>
</template>
```

But if I do that, yes the `$props is undefined` error goes away but my browser still isn't rendering anything. 

sharp-plugin.js
```
import Sharp from 'sharp-plugin';
import TextIcon from './components/TextIcon.vue';

Vue.use(Sharp, {
    customFields: {
        'textIcon': TextIcon
    }
})

window.Vue.config.productionTip = false
window.Vue.config.devtools = true
```

TextIcon.vue
```
<template>
    <div>
        <input class="SharpText" :value="value" @change="handleChanged">
        <i class="fa" :class="icon"></i> 
    </div>
</template>

<script>
export default {
    props: {
        value: String, // field value
        icon: String   // custom added props (given in field definition)
    },
    methods: {
        handleChanged(e) {
            this.$emit('input', e.target.value); // emit input when the value change, form data is updated
        }
    }
}
</script>

```

I am running Laravel 10.28 with Sharp 8.0 and I am using Vite.

**Comment by aguingand** [comment]
Do you compile with `vue-template-compiler` (Vue 2) ?

**Comment by sandervankasteel** [comment]
I just double checked my `package.json` @aguingand, no I don't have that dependency. Is that required ? Or is it a peer dependency of `sharp-plugin`?

**Comment by aguingand** [comment]
We currently only support Vue 2, so you should build with Vue 2 dependencies (vue-loader 15, vue-template-compiler). Vue 3 will be supported in v9

**Comment by sandervankasteel** [comment]
Thanks for your answer. Would you accept a PR with a documentation update on this matter ?

**Comment by aguingand** [comment]
Yes a PR is welcomed !
