### ISSUE TITLE
Sharp Dashboard Doesn't work on chrome

### ISSUE THREAD

**Issue by IlyasDiker** [code16/sharp#519]
Opening the same page it doesn't work on Chrome but works on other browsers This happened to me to on all my projects running on sharp

Example:
![image](https://github.com/code16/sharp/assets/28260951/871e6120-bdab-44f5-938e-a4736453d2f1)

**Comment by aguingand** [comment]
What is the content of your `sharp-plugin.js` file ?

**Comment by IlyasDiker** [comment]
Here is the content of sharp-plugin.js

```js
import Sharp from 'sharp-plugin';
import PhoneField from './sharp-components/Form/Phone.vue';
import PlateField from './sharp-components/Form/Plate.vue';

Vue.use(Sharp, {
    customFields: {
        'phone': PhoneField,
        'plate': PlateField
    }
})

```

**Comment by IlyasDiker** [comment]
I think i've found the issue it's caused by a chrome extension called Word Replacer II when i have the extension it make the page crash and when i remove it, it works.
