### ISSUE TITLE
Custom web route prefix (instead of /sharp)

### ISSUE THREAD

**Issue by irman** [code16/sharp#53]
Hi,

Let me start by thanking u guys. What an awesome package! I just started using it and it works seamlessly so far. Thus, I'll try to help anyway I can.

It would be helpful to have an ability to change the web route prefix (currently hardcoded to: `/sharp`) to something else, probably configurable through `config/sharp.php`.

Let me know what u think about this, I may be able to help out if it's not within your plans.

Thanks!

**Comment by dvlpp** [comment]
Yes, it's in our roadmap for 4.1, with dashboard enhancement and generalization, and data localization. I keep this issue opened and will post here when available.
