### ISSUE TITLE
Replace `Laravel 10` to `Laravel 11` in repository description

### ISSUE THREAD

**Issue by gomzyakov** [code16/sharp#547]
I see in description:

<img width="333" alt="image" src="https://github.com/code16/sharp/assets/1460709/c72f631e-63cd-4662-86df-d96ec9ed7a89">

But Laravel 11 is supported now:

<img width="777" alt="image" src="https://github.com/code16/sharp/assets/1460709/0d7e5036-25d5-4eff-be2f-7573844add49">

**Comment by dvlpp** [comment]
Ah, we wrote 10+ because sharp 8 allows Laravel 10 and 11... I think this is a good way to put it don't you think?

**Comment by gomzyakov** [comment]
@dvlpp 

I apologize for my inattention)

Yes, I agree, 10+ clearly indicates that versions newer than 10 are supported.

I am closing this task.
