### ISSUE TITLE
Using sharp at domain root will crash breadcrumb

### ISSUE THREAD

**Issue by PatrickePatate** [code16/sharp#548]
It looks like if you do not set any `custom_url_segment` in sharp configuration, for an app that is only a dashboard for exemple, the breadcrumb service provider will crash.

![image](https://github.com/code16/sharp/assets/16721134/0cc11c47-5aac-4b15-8cf9-6e561fa08b77)

**Comment by dvlpp** [comment]
Yes... at this moment, Sharp won't work without url_segment: you have to put one.
