### ISSUE TITLE
Ability to show form field only on create or update

### ISSUE THREAD

**Issue by Insolita** [code16/sharp#65]
Is exists way to show form field with dependency based on action type - for create or for update only?

**Comment by dvlpp** [comment]
Yes, there is an undocumented way 😬.

You can use the `Code16\Sharp\Http\WithSharpFormContext` trait, in a List, a Form or a Validator.

And then, call `$this->context()` to gain some context information: is it a form, an update, a creation, what's the instanceId (called `entityId()` by mistake in this class). For instance:

    $this->addField(
            SharpFormTextField::make("key")
                ->setReadOnly($this->context()->isUpdate())
    );

or

    if($this->context()->isCreation()) {
        $this->addField(SharpFormTextField::make("key"))
    }

**Comment by BramEsposito** [comment]
The Trait appears to have changed to ```Code16\Sharp\Http\WithSharpContext``` and ```entityId``` is now ```instanceId```

**Comment by dvlpp** [comment]
Ah yes... This was specified here: https://sharp.code16.fr/docs/guide/upgrading/4.1.3.html. a BC in a minor version, but for an undocumented feature (at the time)
