### ISSUE TITLE
Artisan commands to scaffold new classes?

### ISSUE THREAD

**Issue by siegerhansma** [code16/sharp#66]
Are there any plans to implement artisan commands to scaffold new classes? I'm just getting started with Sharp and I feel like some generators would save a lot of time and keystrokes.

**Comment by dvlpp** [comment]
No plans for now, but sure this would be a great feature to add. To be honest, I don't usually use generators myself (outside migrations), but I can see the value in Sharp case. I'm going to put this aside waiting for some time to look after it, but if you want to make a PR on this, please do!
