### ISSUE TITLE
I don't know where to put classes!

### ISSUE THREAD

**Issue by Mu9tafa-Online** [code16/sharp#76]
Sorry i didn't know where to ask this question, but i don't konw how to start building dashboard (Lists, Forms) .. on the docs there is no mention of **where should i create those classes** ! Help Me.

**Comment by dvlpp** [comment]
Wherever you like... I use an `App/Sharp` namespace, but you can do what you want, as long as you reference these classes in the config (see https://github.com/code16/sharp/blob/master/saturn/config/sharp.php for an example)
