### ISSUE TITLE
Dashboard error after updating to 4.1

### ISSUE THREAD

**Issue by oddvalue** [code16/sharp#85]
Hi,

I've just updated to the latest tag from 4.0 and I'm getting some js errors and my dashboard it broken.

I've followed the upgrade instructions and altered the config for the menu and dashboard. If I go to http://laravel.test/sharp/api/dashboard/dashboard in the browser I get the expected json response but for some reason the dashboard is attempting to load http://laravel.test/sharp/api/dashboard.

Any ideas what's going on here? 

![image](https://user-images.githubusercontent.com/10127404/52204384-ecbe0a80-286b-11e9-9f1b-d321911b5870.png)

Config file:

```php
<?php
return [
    'dashboards' => [
        'dashboard' => [
            'view' => \App\Sharp\Dashboard::class,
        ]
    ],
    'entities' => [
        ...
    ],
    'menu' => [
        [
            'label' => 'Dashboard',
            'icon' => 'fa-dashboard',
            'dashboard' => 'dashboard',
        ],
    ],
];
```

**Comment by oddvalue** [comment]
My bad, needed to completely clear the assets published from the sharp package and re-publish. Have it working now.

**Comment by dvlpp** [comment]
Yeah, a good practice to avoid this is to add a `php artisan vendor:publish` in your `composer.json` scripts. Since Sharp use its version number in the asset URL querystring, cache should never be an issue.
 
```json
"scripts": {
   "post-autoload-dump": [
        "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
        "@php artisan vendor:publish --tag=assets --force",
        "@php artisan package:discover"
    ]
},
```
