### ISSUE TITLE
Thumbnail path wrong

### ISSUE THREAD

**Issue by oddvalue** [code16/sharp#94]
Hi,

Since this commit https://github.com/code16/sharp/commit/2f8140d924e5bd0fd26d98a59b1366c72bb6f57c all thumbnail urls have stopped working.

The issue seems to be that the images were previously stored in the public directory `public/thumbnails/...` and so were served without any problems. Now they are stored under `storage/public/thumbnails/...`.
I do have the symlink set up to map `storage/public/` to `public/storage/` so if I add "storage" to the url it loads the image but the url returned from the thumbnail method doesn't contain it so the image isn't loaded. 

e.g
URL returned from the thumbnail method that 404s:
http://laravel.test/thumbnails/images/300-300/image.jpeg

URL with "storage" added that works:
http://laravel.test/storage/thumbnails/images/300-300/image.jpeg

How are you handling this in your projects? Is there a new step missing from the readme?

Thanks

**Comment by dvlpp** [comment]
Hi,
What's in your sharp.php config file regarding thumbnails? 
(in the "uploads" section)

**Comment by oddvalue** [comment]
My config looks like this:

```
    'uploads' => [
        'thumbnails_dir' => 'thumbnails',
    ],
```
Thanks

**Comment by dvlpp** [comment]
Mmm, maybe your `public` disk config (in `config/filesystems.php`) is out of sync? I have:

```
'public' => [
    'driver' => 'local',
    'root' => storage_path('app/public'),
    'url' => env('APP_URL').'/storage',
    'visibility' => 'public',
],
```

**Comment by oddvalue** [comment]
I don't think it's that. I have the same:

```
'public' => [
    'driver' => 'local',
    'root' => storage_path('app/public'),
    'url' => env('APP_URL').'/storage',
    'visibility' => 'public',
],
```

What would you expect the URL for a thumbnail to look like once generated? Should it have the "storage" bit in it?

**Comment by dvlpp** [comment]
Are you usign a VM like Homestead? Maybe the symlink is not working because it was made on the dev machine instead of into the VM?

**Comment by oddvalue** [comment]
I'm using docker but I don't have any issues with the symlinks. 
As a temporary solution I've added a symlink from `./storage/app/public/thumbnails` to `./public/thumbnails` and everything works fine. 
I don't see how the symlinks are supposed to work without that since the images are saved in `./storage/app/public/thumbnails` but for the standard storage symlink in Laravel to work the URL returned by the `thumbnail` method would have to point to `/storage/thumbnails/...` not just `/thumbnails/...` as it does currently.

**Comment by dvlpp** [comment]
I'm confused by this issue, because I don't understand how this was working for me... Anyway I used `Storage::url()` to grab the real thumbnail url, and I should have done this when I've updated this feature on the commit you mentioned. Can you try it again with the latest master version?

**Comment by oddvalue** [comment]
Yeah, that seems to have done the trick. I would have submitted a pull request for that but I was also confused as to how it was working for you if you weren't experiencing the issue. 
Anyway, thanks for sorting!
