### ISSUE TITLE
Dump data

### ISSUE THREAD

**Issue by rokkay** [code16/sharp#95]
Hi, im using Sharp for a project, its a powerful tool but sometimes i feel a bit lost. I dont know how to to dump data after create/update a record. I tried with dd(), dump() and [barryvdh/laravel-debugbar](https://github.com/barryvdh/laravel-debugbar) package.  I have .env debug to true but nothings works.

Thanks in advance.

**Comment by dvlpp** [comment]
Hi,
Sharp heavily uses XHR / Ajax requests for this kind of things — meaning your dd() result should be visible in your browser's console (network tab, the POST request). Note that you could also use a package like this one https://github.com/beyondcode/laravel-dump-server to dump your data on the console.

**Comment by irman** [comment]
[Laravel Telescope](https://laravel.com/docs/5.7/telescope) is a good alternative too.
